import { useEffect, useMemo, useRef, useState } from "react";
import { scoreLead, scoreBucket } from "./leadEngine";
import { generateMarketing } from "./marketingEngine";

type Language = "English" | "Spanish" | "French" | "German" | "Portuguese";
type PlanTier = "basic" | "pro" | "team";

type Customer = {
  name: string;
  created: string;
};

type LeadRow = {
  id: string;
  title: string;
  description: string;
  city: string;
  source: string;
  contact_name: string;
  contact_info: string;
  budget: string;
  score: number;
  status: string;
  created_at: string;
};

type EstimateData = {
  jobType: string;
  laborHours: number;
  laborRate: number;
  laborCost: number;
  materialsCost: number;
  equipmentCost: number;
  subtotal: number;
  markupPercent: number;
  markupAmount: number;
  total: number;
  scope: string;
  recommendations: string[];
};

declare global {
  interface Window {
    supabase: any;
  }
}

const BASIC_STRIPE_LINK = "https://buy.stripe.com/6oU3cocrv2Cb7BW7U1d7q06";
const PRO_STRIPE_LINK = "https://buy.stripe.com/eVqdR21MRfoX3lGeipd7q07";
const TEAM_STRIPE_LINK = "https://buy.stripe.com/3cI9AM77b2Cb2hCcahd7q08";

const SUPABASE_URL = "https://ljizlaabarhyzocfcsba.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqaXpsYWFiYXJoeXpvY2Zjc2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1ODcxNTIsImV4cCI6MjA4OTE2MzE1Mn0.eJstZOcLE_BALH1JMhju4zQonRxMQwk5DbEXpYUIKbw";

const LANGUAGES: Language[] = [
  "English",
  "Spanish",
  "French",
  "German",
  "Portuguese",
];

const languageLabels: Record<
  Language,
  {
    estimateTitle: string;
    estimateFor: string;
    customer: string;
    jobDescription: string;
    detectedJobType: string;
    scopeOfWork: string;
    laborHours: string;
    laborRate: string;
    laborCost: string;
    materialsCost: string;
    equipmentCost: string;
    subtotal: string;
    markup: string;
    totalEstimate: string;
    recommendations: string;
    generatedBy: string;
    currencyNote: string;
  }
> = {
  English: {
    estimateTitle: "PROFESSIONAL ESTIMATE",
    estimateFor: "Estimate For",
    customer: "Customer",
    jobDescription: "Job Description",
    detectedJobType: "Detected Job Type",
    scopeOfWork: "Scope of Work",
    laborHours: "Estimated Labor Hours",
    laborRate: "Labor Rate",
    laborCost: "Labor Cost",
    materialsCost: "Materials Cost",
    equipmentCost: "Equipment Cost",
    subtotal: "Subtotal",
    markup: "Markup",
    totalEstimate: "Total Estimate",
    recommendations: "Recommendations",
    generatedBy: "Generated by Tradesman AI",
    currencyNote:
      "All pricing is an estimate and should be reviewed before sending.",
  },
  Spanish: {
    estimateTitle: "PRESUPUESTO PROFESIONAL",
    estimateFor: "Presupuesto Para",
    customer: "Cliente",
    jobDescription: "Descripción del Trabajo",
    detectedJobType: "Tipo de Trabajo Detectado",
    scopeOfWork: "Alcance del Trabajo",
    laborHours: "Horas de Mano de Obra Estimadas",
    laborRate: "Tarifa de Mano de Obra",
    laborCost: "Costo de Mano de Obra",
    materialsCost: "Costo de Materiales",
    equipmentCost: "Costo de Equipo",
    subtotal: "Subtotal",
    markup: "Margen",
    totalEstimate: "Presupuesto Total",
    recommendations: "Recomendaciones",
    generatedBy: "Generado por Tradesman AI",
    currencyNote:
      "Todos los precios son estimados y deben revisarse antes de enviarlos.",
  },
  French: {
    estimateTitle: "DEVIS PROFESSIONNEL",
    estimateFor: "Devis Pour",
    customer: "Client",
    jobDescription: "Description du Travail",
    detectedJobType: "Type de Travail Détecté",
    scopeOfWork: "Étendue des Travaux",
    laborHours: "Heures de Main-d'œuvre Estimées",
    laborRate: "Taux de Main-d'œuvre",
    laborCost: "Coût de Main-d'œuvre",
    materialsCost: "Coût des Matériaux",
    equipmentCost: "Coût de l'Équipement",
    subtotal: "Sous-total",
    markup: "Marge",
    totalEstimate: "Devis Total",
    recommendations: "Recommandations",
    generatedBy: "Généré par Tradesman AI",
    currencyNote:
      "Tous les prix sont estimatifs et doivent être vérifiés avant envoi.",
  },
  German: {
    estimateTitle: "PROFESSIONELLES ANGEBOT",
    estimateFor: "Angebot Für",
    customer: "Kunde",
    jobDescription: "Arbeitsbeschreibung",
    detectedJobType: "Erkannter Arbeitstyp",
    scopeOfWork: "Leistungsumfang",
    laborHours: "Geschätzte Arbeitsstunden",
    laborRate: "Stundensatz",
    laborCost: "Arbeitskosten",
    materialsCost: "Materialkosten",
    equipmentCost: "Gerätekosten",
    subtotal: "Zwischensumme",
    markup: "Aufschlag",
    totalEstimate: "Gesamtangebot",
    recommendations: "Empfehlungen",
    generatedBy: "Erstellt von Tradesman AI",
    currencyNote:
      "Alle Preise sind Schätzungen und sollten vor dem Versand geprüft werden.",
  },
  Portuguese: {
    estimateTitle: "ORÇAMENTO PROFISSIONAL",
    estimateFor: "Orçamento Para",
    customer: "Cliente",
    jobDescription: "Descrição do Serviço",
    detectedJobType: "Tipo de Serviço Detectado",
    scopeOfWork: "Escopo do Trabalho",
    laborHours: "Horas de Mão de Obra Estimadas",
    laborRate: "Taxa de Mão de Obra",
    laborCost: "Custo de Mão de Obra",
    materialsCost: "Custo de Materiais",
    equipmentCost: "Custo de Equipamento",
    subtotal: "Subtotal",
    markup: "Margem",
    totalEstimate: "Orçamento Total",
    recommendations: "Recomendações",
    generatedBy: "Gerado por Tradesman AI",
    currencyNote:
      "Todos os preços são estimados e devem ser revisados antes do envio.",
  },
};

function money(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 2,
  }).format(value);
}

function getPlanRank(plan: PlanTier): number {
  if (plan === "team") return 3;
  if (plan === "pro") return 2;
  return 1;
}

function hasAccess(current: PlanTier, needed: PlanTier): boolean {
  return getPlanRank(current) >= getPlanRank(needed);
}

function detectJobType(description: string): string {
  const text = description.toLowerCase();
  if (text.includes("fence")) return "Fence Work";
  if (text.includes("gravel") || text.includes("road base")) return "Gravel / Base Work";
  if (text.includes("driveway")) return "Driveway Work";
  if (text.includes("pad")) return "Pad Prep";
  if (text.includes("brush") || text.includes("clear")) return "Brush Clearing";
  if (text.includes("concrete")) return "Concrete Work";
  if (text.includes("demo") || text.includes("demolition") || text.includes("remove")) {
    return "Demolition / Removal";
  }
  if (text.includes("excavat") || text.includes("dig") || text.includes("trench")) {
    return "Excavation";
  }
  if (text.includes("alternator") || text.includes("repair") || text.includes("mechanic")) {
    return "Mechanical Repair";
  }
  return "General Contract Work";
}

function parseDimensionMultiplier(description: string): number {
  const match = description.match(/(\d+)\s*x\s*(\d+)/i);
  if (!match) return 1;
  const a = Number(match[1]);
  const b = Number(match[2]);
  if (!Number.isFinite(a) || !Number.isFinite(b)) return 1;
  const area = a * b;
  if (area <= 400) return 1;
  if (area <= 1200) return 1.35;
  if (area <= 2500) return 1.75;
  return 2.2;
}

function generateEstimateData(
  description: string,
  customLaborRate?: number,
  customMarkupPercent?: number
): EstimateData {
  const text = description.toLowerCase().trim();
  const jobType = detectJobType(description);
  const sizeMultiplier = parseDimensionMultiplier(description);

  let laborHours = 6;
  let laborRate = customLaborRate ?? 95;
  let materialsCost = 250;
  let equipmentCost = 200;
  const markupPercent = customMarkupPercent ?? 20;
  let scope =
    "Provide labor, tools, equipment, setup, cleanup, and standard job completion based on the described work.";

  const recommendations: string[] = [];

  if (text.includes("gravel") || text.includes("road base")) {
    laborHours = 10;
    materialsCost = 1200;
    equipmentCost = 550;
    scope =
      "Supply, spread, grade, and compact gravel or base material to the requested area.";
    recommendations.push("Verify haul distance and material availability.");
    recommendations.push("Confirm final grade and compaction requirements.");
  }

  if (text.includes("driveway")) {
    laborHours = 12;
    materialsCost += 900;
    equipmentCost += 400;
    scope =
      "Prepare driveway area, place material, grade surface, and leave site ready for use.";
    recommendations.push("Measure actual driveway length and width before final quote.");
  }

  if (text.includes("pad")) {
    laborHours = 14;
    materialsCost += 1300;
    equipmentCost += 500;
    scope =
      "Prepare pad area, grade, compact, and place material suitable for slab or structure support.";
    recommendations.push("Check subgrade condition and drainage before final pricing.");
  }

  if (text.includes("fence")) {
    laborHours = 16;
    materialsCost = 1400;
    equipmentCost = 180;
    scope =
      "Remove or install fence components, set posts, align runs, and complete standard fence work.";
    recommendations.push("Verify footage, gate count, and post spacing.");
  }

  if (text.includes("brush") || text.includes("clear")) {
    laborHours = 14;
    materialsCost = 180;
    equipmentCost = 750;
    scope =
      "Clear brush, vegetation, and light debris from the requested work area.";
    recommendations.push("Confirm dump/disposal expectations and access conditions.");
  }

  if (text.includes("concrete")) {
    laborHours = 18;
    materialsCost += 2200;
    equipmentCost += 650;
    scope =
      "Perform concrete-related removal, prep, placement, or finishing based on the described work.";
    recommendations.push("Verify thickness, reinforcement, and finish type.");
  }

  if (text.includes("demo") || text.includes("demolition") || text.includes("remove")) {
    laborHours += 8;
    equipmentCost += 450;
    materialsCost += 150;
    recommendations.push("Confirm disposal fees and haul-off distance.");
  }

  if (text.includes("excavat") || text.includes("dig") || text.includes("trench")) {
    laborHours += 10;
    equipmentCost += 800;
    materialsCost += 100;
    scope =
      "Excavate, shape, and clean the work area to the described dimensions and purpose.";
    recommendations.push("Call utility locate before digging.");
  }

  if (text.includes("alternator") || text.includes("repair") || text.includes("mechanic")) {
    laborHours = 4;
    laborRate = customLaborRate ?? 110;
    materialsCost = 380;
    equipmentCost = 60;
    scope =
      "Diagnose, remove, replace, test, and verify proper operation for the described repair.";
    recommendations.push("Confirm exact part number before ordering.");
  }

  laborHours = Math.round(laborHours * sizeMultiplier);
  materialsCost = Math.round(materialsCost * sizeMultiplier);
  equipmentCost = Math.round(equipmentCost * Math.min(sizeMultiplier, 1.8));

  const laborCost = laborHours * laborRate;
  const subtotal = laborCost + materialsCost + equipmentCost;
  const markupAmount = Math.round(subtotal * (markupPercent / 100));
  const total = subtotal + markupAmount;

  if (recommendations.length === 0) {
    recommendations.push("Verify final measurements on site.");
    recommendations.push("Confirm material pricing before sending.");
  }

  return {
    jobType,
    laborHours,
    laborRate,
    laborCost,
    materialsCost,
    equipmentCost,
    subtotal,
    markupPercent,
    markupAmount,
    total,
    scope,
    recommendations,
  };
}

function formatEstimate(
  data: EstimateData,
  customerName: string,
  description: string,
  language: Language
): string {
  const t = languageLabels[language];

  return `${t.estimateTitle}

${t.estimateFor}: ${customerName || "Walk-in / Unassigned"}

${t.customer}: ${customerName || "Not specified"}
${t.jobDescription}: ${description}
${t.detectedJobType}: ${data.jobType}

${t.scopeOfWork}:
${data.scope}

${t.laborHours}: ${data.laborHours}
${t.laborRate}: ${money(data.laborRate)}
${t.laborCost}: ${money(data.laborCost)}
${t.materialsCost}: ${money(data.materialsCost)}
${t.equipmentCost}: ${money(data.equipmentCost)}
${t.subtotal}: ${money(data.subtotal)}
${t.markup}: ${data.markupPercent}% (${money(data.markupAmount)})

${t.totalEstimate}: ${money(data.total)}

${t.recommendations}:
- ${data.recommendations.join("\n- ")}

${t.generatedBy}
${t.currencyNote}`;
}

function translateText(text: string, language: Language): string {
  if (language === "English") return text;

  const replacements: Record<Language, Array<[string, string]>> = {
    English: [],
    Spanish: [
      ["PROFESSIONAL ESTIMATE", "PRESUPUESTO PROFESIONAL"],
      ["Estimate For", "Presupuesto Para"],
      ["Customer", "Cliente"],
      ["Job Description", "Descripción del Trabajo"],
      ["Detected Job Type", "Tipo de Trabajo Detectado"],
      ["Scope of Work", "Alcance del Trabajo"],
      ["Estimated Labor Hours", "Horas de Mano de Obra Estimadas"],
      ["Labor Rate", "Tarifa de Mano de Obra"],
      ["Labor Cost", "Costo de Mano de Obra"],
      ["Materials Cost", "Costo de Materiales"],
      ["Equipment Cost", "Costo de Equipo"],
      ["Subtotal", "Subtotal"],
      ["Markup", "Margen"],
      ["Total Estimate", "Presupuesto Total"],
      ["Recommendations", "Recomendaciones"],
      ["Generated by Tradesman AI", "Generado por Tradesman AI"],
      ["Not specified", "No especificado"],
      ["Walk-in / Unassigned", "Cliente sin asignar"],
    ],
    French: [
      ["PROFESSIONAL ESTIMATE", "DEVIS PROFESSIONNEL"],
      ["Estimate For", "Devis Pour"],
      ["Customer", "Client"],
      ["Job Description", "Description du Travail"],
      ["Detected Job Type", "Type de Travail Détecté"],
      ["Scope of Work", "Étendue des Travaux"],
      ["Estimated Labor Hours", "Heures de Main-d'œuvre Estimées"],
      ["Labor Rate", "Taux de Main-d'œuvre"],
      ["Labor Cost", "Coût de Main-d'œuvre"],
      ["Materials Cost", "Coût des Matériaux"],
      ["Equipment Cost", "Coût de l'Équipement"],
      ["Subtotal", "Sous-total"],
      ["Markup", "Marge"],
      ["Total Estimate", "Devis Total"],
      ["Recommendations", "Recommandations"],
      ["Generated by Tradesman AI", "Généré par Tradesman AI"],
      ["Not specified", "Non spécifié"],
      ["Walk-in / Unassigned", "Client non attribué"],
    ],
    German: [
      ["PROFESSIONAL ESTIMATE", "PROFESSIONELLES ANGEBOT"],
      ["Estimate For", "Angebot Für"],
      ["Customer", "Kunde"],
      ["Job Description", "Arbeitsbeschreibung"],
      ["Detected Job Type", "Erkannter Arbeitstyp"],
      ["Scope of Work", "Leistungsumfang"],
      ["Estimated Labor Hours", "Geschätzte Arbeitsstunden"],
      ["Labor Rate", "Stundensatz"],
      ["Labor Cost", "Arbeitskosten"],
      ["Materials Cost", "Materialkosten"],
      ["Equipment Cost", "Gerätekosten"],
      ["Subtotal", "Zwischensumme"],
      ["Markup", "Aufschlag"],
      ["Total Estimate", "Gesamtangebot"],
      ["Recommendations", "Empfehlungen"],
      ["Generated by Tradesman AI", "Erstellt von Tradesman AI"],
      ["Not specified", "Nicht angegeben"],
      ["Walk-in / Unassigned", "Nicht zugeordnet"],
    ],
    Portuguese: [
      ["PROFESSIONAL ESTIMATE", "ORÇAMENTO PROFISSIONAL"],
      ["Estimate For", "Orçamento Para"],
      ["Customer", "Cliente"],
      ["Job Description", "Descrição do Serviço"],
      ["Detected Job Type", "Tipo de Serviço Detectado"],
      ["Scope of Work", "Escopo do Trabalho"],
      ["Estimated Labor Hours", "Horas de Mão de Obra Estimadas"],
      ["Labor Rate", "Taxa de Mão de Obra"],
      ["Labor Cost", "Custo de Mão de Obra"],
      ["Materials Cost", "Custo de Materiais"],
      ["Equipment Cost", "Custo de Equipamento"],
      ["Subtotal", "Subtotal"],
      ["Markup", "Margem"],
      ["Total Estimate", "Orçamento Total"],
      ["Recommendations", "Recomendações"],
      ["Generated by Tradesman AI", "Gerado por Tradesman AI"],
      ["Not specified", "Não especificado"],
      ["Walk-in / Unassigned", "Cliente não atribuído"],
    ],
  };

  let result = text;
  for (const [from, to] of replacements[language]) {
    result = result.split(from).join(to);
  }
  return result;
}

function quoteRangeFromLead(
  description: string,
  score: number,
  laborRate?: number,
  markupPercent?: number
): string {
  const estimate = generateEstimateData(
    description || "General contractor job",
    laborRate,
    markupPercent
  );

  let low = Math.round(estimate.total * 0.85);
  let high = Math.round(estimate.total * 1.2);

  if (detectJobType(description) === "Mechanical Repair") {
    low = Math.round(estimate.total * 0.9);
    high = Math.round(estimate.total * 1.1);
  }

  if (score >= 70) {
    low = Math.round(low * 1.05);
    high = Math.round(high * 1.1);
  }

  return `${money(low)} - ${money(high)}`;
}

function buildContractorInboxAssistant(
  lead: {
    title: string;
    description: string;
    city: string;
    contactName: string;
    contactInfo: string;
    budget: string;
  },
  laborRate: number,
  markupPercent: number
) {
  const combined = `${lead.title}\n${lead.description}\n${lead.city}\n${lead.budget}\n${lead.contactName}\n${lead.contactInfo}`;
  const scored = scoreLead(combined);
  const bucket = scoreBucket(scored.score);
  const jobType = detectJobType(`${lead.title} ${lead.description}`);
  const range = quoteRangeFromLead(
    `${lead.title}\n${lead.description}`,
    scored.score,
    laborRate,
    markupPercent
  );

  const quickReply = `Hi ${lead.contactName || "there"} — thanks for reaching out about your ${jobType.toLowerCase()} project${lead.city ? ` in ${lead.city}` : ""}. Based on what you sent, this looks like a rough range of ${range}. If you'd like, I can take a closer look and get you a firm quote.`;

  const followUp = `Hi ${lead.contactName || "there"} — just following up on your ${jobType.toLowerCase()} project${lead.city ? ` in ${lead.city}` : ""}. I can get this moving for you and help dial in the exact scope and final quote. Let me know if you'd like me to put together the next step.`;

  const closeAngle =
    bucket === "Hot"
      ? "Lead looks strong. Fast response is the priority."
      : bucket === "Warm"
      ? "Lead has potential. Clarify timeline, access, and exact scope."
      : "Lower intent lead. Keep reply short and qualify the project fast.";

  return {
    score: scored.score,
    bucket,
    reasons: scored.reasons,
    jobType,
    range,
    quickReply,
    followUp,
    closeAngle,
  };
}

export default function App() {
  const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

  const [session, setSession] = useState<any>(null);
  const [authLoading, setAuthLoading] = useState(true);
  const [authMode, setAuthMode] = useState<"signin" | "signup">("signin");
  const [authEmail, setAuthEmail] = useState("");
  const [authPassword, setAuthPassword] = useState("");
  const [authMessage, setAuthMessage] = useState("");

  const [plan, setPlan] = useState<PlanTier>("basic");

  const [customers, setCustomers] = useState<Customer[]>([]);
  const [customerName, setCustomerName] = useState("");
  const [selectedCustomer, setSelectedCustomer] = useState("");

  const [jobDescription, setJobDescription] = useState("");
  const [language, setLanguage] = useState<Language>("English");
  const [translateLanguage, setTranslateLanguage] = useState<Language>("Spanish");
  const [output, setOutput] = useState("");
  const [translationPreview, setTranslationPreview] = useState("");
  const [selectedText, setSelectedText] = useState("");

  const [leadTitle, setLeadTitle] = useState("");
  const [leadDescription, setLeadDescription] = useState("");
  const [leadCity, setLeadCity] = useState("");
  const [leadContactName, setLeadContactName] = useState("");
  const [leadContactInfo, setLeadContactInfo] = useState("");
  const [leadBudget, setLeadBudget] = useState("");
  const [leads, setLeads] = useState<LeadRow[]>([]);
  const [leadStatusFilter, setLeadStatusFilter] = useState("all");
  const [leadBucketFilter, setLeadBucketFilter] = useState("all");

  const [marketingJob, setMarketingJob] = useState("");
  const [marketingCity, setMarketingCity] = useState("");
  const [marketingOutput, setMarketingOutput] = useState("");

  const [companyName, setCompanyName] = useState(
    () => localStorage.getItem("companyName") || ""
  );
  const [laborRateSetting, setLaborRateSetting] = useState<number>(() => {
    const stored = localStorage.getItem("laborRateSetting");
    return stored ? Number(stored) : 95;
  });
  const [markupSetting, setMarkupSetting] = useState<number>(() => {
    const stored = localStorage.getItem("markupSetting");
    return stored ? Number(stored) : 20;
  });
  const [freeEstimateUses, setFreeEstimateUses] = useState<number>(() => {
    const stored = localStorage.getItem("freeEstimateUses");
    return stored ? Number(stored) : 0;
  });

  const outputRef = useRef<HTMLTextAreaElement | null>(null);

  const primaryButtonStyle = {
    background: "#6366f1",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    padding: "11px 16px",
    cursor: "pointer",
    fontWeight: 800,
  };

  const secondaryButtonStyle = {
    background: "#fff",
    color: "#111827",
    border: "1px solid #d1d5db",
    borderRadius: 12,
    padding: "11px 16px",
    cursor: "pointer",
    fontWeight: 800,
  };

  const inputStyle = {
    width: "100%",
    padding: 12,
    borderRadius: 12,
    border: "1px solid #d1d5db",
    boxSizing: "border-box" as const,
  };

  useEffect(() => {
    localStorage.setItem("companyName", companyName);
  }, [companyName]);

  useEffect(() => {
    localStorage.setItem("laborRateSetting", String(laborRateSetting));
  }, [laborRateSetting]);

  useEffect(() => {
    localStorage.setItem("markupSetting", String(markupSetting));
  }, [markupSetting]);

  useEffect(() => {
    localStorage.setItem("freeEstimateUses", String(freeEstimateUses));
  }, [freeEstimateUses]);

  useEffect(() => {
    let mounted = true;

    supabase.auth.getSession().then((result: any) => {
      if (!mounted) return;
      setSession(result?.data?.session ?? null);
      setAuthLoading(false);
    });

    const authListener = supabase.auth.onAuthStateChange(
      (_event: any, nextSession: any) => {
        setSession(nextSession);
        setAuthLoading(false);
      }
    );

    return () => {
      mounted = false;
      authListener?.data?.subscription?.unsubscribe?.();
    };
  }, [supabase.auth]);

  useEffect(() => {
    if (session?.user?.id) {
      void loadLeads(session.user.id);
    } else {
      setLeads([]);
    }
  }, [session]);

  async function loadLeads(userId: string) {
    const result = await supabase
      .from("leads")
      .select("*")
      .eq("user_id", userId)
      .order("score", { ascending: false })
      .order("created_at", { ascending: false });

    if (!result.error) {
      const mapped = (result.data || []).map((row: any) => ({
        ...row,
        created_at: row.created_at
          ? new Date(row.created_at).toLocaleString()
          : "",
      }));
      setLeads(mapped);
    }
  }

  async function handleSignUp() {
    setAuthMessage("");
    if (!authEmail || !authPassword) {
      setAuthMessage("Enter email and password.");
      return;
    }

    const result = await supabase.auth.signUp({
      email: authEmail,
      password: authPassword,
      options: {
        emailRedirectTo: window.location.origin,
      },
    });

    if (result.error) {
      setAuthMessage(result.error.message);
      return;
    }

    setAuthMessage("Account created. Check your email if confirmation is required.");
  }

  async function handleSignIn() {
    setAuthMessage("");
    if (!authEmail || !authPassword) {
      setAuthMessage("Enter email and password.");
      return;
    }

    const result = await supabase.auth.signInWithPassword({
      email: authEmail,
      password: authPassword,
    });

    if (result.error) {
      setAuthMessage(result.error.message);
      return;
    }

    setAuthMessage("Signed in.");
  }

  async function handleSignOut() {
    await supabase.auth.signOut();
    setAuthMessage("");
  }

  async function addLead() {
    if (!session?.user?.id) {
      alert("Sign in first.");
      return;
    }

    if (!hasAccess(plan, "pro")) {
      alert("Lead Inbox is a Pro or Team feature.");
      return;
    }

    const combined = `${leadTitle}\n${leadDescription}\n${leadCity}\n${leadBudget}\n${leadContactName}\n${leadContactInfo}`;
    const scored = scoreLead(combined);

    const result = await supabase.from("leads").insert({
      user_id: session.user.id,
      source: "manual",
      title: leadTitle,
      description: leadDescription,
      city: leadCity,
      contact_name: leadContactName,
      contact_info: leadContactInfo,
      budget: leadBudget,
      score: scored.score,
      status: "new",
    });

    if (result.error) {
      alert(result.error.message);
      return;
    }

    setLeadTitle("");
    setLeadDescription("");
    setLeadCity("");
    setLeadContactName("");
    setLeadContactInfo("");
    setLeadBudget("");

    await loadLeads(session.user.id);
  }

  async function updateLeadStatus(id: string, status: string) {
    if (!session?.user?.id) return;

    const result = await supabase.from("leads").update({ status }).eq("id", id);
    if (result.error) {
      alert(result.error.message);
      return;
    }

    await loadLeads(session.user.id);
  }

  async function deleteLead(id: string) {
    if (!session?.user?.id) return;

    const result = await supabase.from("leads").delete().eq("id", id);
    if (result.error) {
      alert(result.error.message);
      return;
    }

    await loadLeads(session.user.id);
  }

  function buildMarketing() {
    if (!hasAccess(plan, "pro")) {
      alert("AI Marketing Generator is a Pro or Team feature.");
      return;
    }

    const result = generateMarketing(marketingJob, marketingCity);

    const text = `MARKETING CONTENT

HOOK
${result.hook}

FACEBOOK AD
${result.facebookAd}

GOOGLE AD
${result.googleAd}

SOCIAL POST
${result.socialPost}

SPECIAL OFFER
${result.offer}
`;

    setMarketingOutput(text);
  }

  function generateFrontDoorEstimate() {
    if (!session && freeEstimateUses >= 3) {
      setOutput(
        "You have used your 3 free estimates. Upgrade to continue with unlimited estimates, lead tools, and AI marketing."
      );
      return;
    }

    const estimate = generateEstimateData(
      jobDescription || "General contractor job",
      laborRateSetting,
      markupSetting
    );

    const customerLabel = companyName || selectedCustomer || "Walk-in / Unassigned";
    const text = formatEstimate(
      estimate,
      customerLabel,
      jobDescription || "General contractor job",
      language
    );

    setOutput(text);
    setTranslationPreview("");

    if (!session) {
      setFreeEstimateUses((prev) => prev + 1);
    }
  }

  const liveEstimate = useMemo(() => {
    return generateEstimateData(
      jobDescription || "General contractor job",
      laborRateSetting,
      markupSetting
    );
  }, [jobDescription, laborRateSetting, markupSetting]);

  const inboxAssistant = useMemo(() => {
    return buildContractorInboxAssistant(
      {
        title: leadTitle,
        description: leadDescription,
        city: leadCity,
        contactName: leadContactName,
        contactInfo: leadContactInfo,
        budget: leadBudget,
      },
      laborRateSetting,
      markupSetting
    );
  }, [
    leadTitle,
    leadDescription,
    leadCity,
    leadContactName,
    leadContactInfo,
    leadBudget,
    laborRateSetting,
    markupSetting,
  ]);

  const filteredLeads = useMemo(() => {
    return leads.filter((lead) => {
      const statusPass =
        leadStatusFilter === "all" ? true : lead.status === leadStatusFilter;
      const bucketPass =
        leadBucketFilter === "all"
          ? true
          : scoreBucket(Number(lead.score || 0)) === leadBucketFilter;
      return statusPass && bucketPass;
    });
  }, [leads, leadStatusFilter, leadBucketFilter]);

  const hotLeads = useMemo(
    () => filteredLeads.filter((lead) => scoreBucket(Number(lead.score || 0)) === "Hot"),
    [filteredLeads]
  );
  const warmLeads = useMemo(
    () => filteredLeads.filter((lead) => scoreBucket(Number(lead.score || 0)) === "Warm"),
    [filteredLeads]
  );
  const coldLeads = useMemo(
    () => filteredLeads.filter((lead) => scoreBucket(Number(lead.score || 0)) === "Cold"),
    [filteredLeads]
  );

  const leadStats = useMemo(() => {
    return {
      total: leads.length,
      hot: leads.filter((l) => scoreBucket(Number(l.score || 0)) === "Hot").length,
      quoted: leads.filter((l) => l.status === "quoted").length,
      won: leads.filter((l) => l.status === "won").length,
    };
  }, [leads]);

  const addCustomer = () => {
    if (!customerName.trim()) return;
    setCustomers((prev) => [
      ...prev,
      {
        name: customerName.trim(),
        created: new Date().toLocaleDateString(),
      },
    ]);
    setCustomerName("");
  };

  const copyOutput = async () => {
    await navigator.clipboard.writeText(output);
  };

  const translateFullOutput = () => {
    if (!output.trim()) return;
    const translated = translateText(output, translateLanguage);
    setOutput(translated);
    setTranslationPreview(translated);
  };

  const handleSelection = () => {
    const textarea = outputRef.current;
    if (!textarea) return;
    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const text = textarea.value.substring(start, end);
    setSelectedText(text);
  };

  const translateSelectedText = () => {
    const textarea = outputRef.current;
    if (!textarea) return;
    if (!selectedText.trim()) return;

    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const translatedSelection = translateText(selectedText, translateLanguage);

    const newOutput =
      output.substring(0, start) + translatedSelection + output.substring(end);

    setOutput(newOutput);
    setTranslationPreview(translatedSelection);
  };

  const replaceAllWithTranslatedPreview = () => {
    if (!translationPreview.trim()) return;
    setOutput(translationPreview);
  };

  if (authLoading) {
    return <div style={{ padding: 32, color: "white" }}>Loading...</div>;
  }

  return (
    <div
      style={{
        minHeight: "100vh",
        fontFamily: "Arial, sans-serif",
        background:
          "radial-gradient(circle at top left, rgba(99,102,241,0.22), transparent 28%), radial-gradient(circle at top right, rgba(236,72,153,0.18), transparent 24%), linear-gradient(180deg, #0b1020 0%, #121a2f 100%)",
        color: "#111827",
      }}
    >
      <div style={{ maxWidth: 1220, margin: "0 auto", padding: 28 }}>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1.15fr 0.85fr",
            gap: 20,
            marginBottom: 24,
          }}
        >
          <div
            style={{
              background:
                "linear-gradient(135deg, rgba(79,70,229,0.95), rgba(168,85,247,0.92), rgba(236,72,153,0.86))",
              borderRadius: 24,
              padding: 28,
              color: "white",
              boxShadow: "0 20px 60px rgba(10, 14, 30, 0.35)",
            }}
          >
            <div
              style={{
                display: "inline-block",
                padding: "8px 12px",
                borderRadius: 999,
                background: "rgba(255,255,255,0.15)",
                fontWeight: 800,
                marginBottom: 16,
              }}
            >
              Instant Estimates + Contractor Inbox Assistant
            </div>

            <h1 style={{ fontSize: 44, lineHeight: 1.05, margin: "0 0 14px" }}>
              Close more jobs faster.
            </h1>

            <p
              style={{
                fontSize: 18,
                lineHeight: 1.7,
                margin: 0,
                color: "rgba(255,255,255,0.92)",
              }}
            >
              Generate professional estimates in seconds, score incoming leads,
              write quick replies, follow up faster, and turn slow quote flow into
              a real closing system.
            </p>

            <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginTop: 18 }}>
              <div
                style={{
                  padding: "10px 12px",
                  borderRadius: 999,
                  background: "rgba(99,102,241,0.16)",
                  border: "1px solid rgba(99,102,241,0.35)",
                  color: "#e5e7eb",
                  fontSize: 13,
                  fontWeight: 700,
                }}
              >
                Instant estimate generator
              </div>
              <div
                style={{
                  padding: "10px 12px",
                  borderRadius: 999,
                  background: "rgba(244,114,182,0.15)",
                  border: "1px solid rgba(244,114,182,0.35)",
                  color: "#e5e7eb",
                  fontSize: 13,
                  fontWeight: 700,
                }}
              >
                Contractor inbox assistant
              </div>
              <div
                style={{
                  padding: "10px 12px",
                  borderRadius: 999,
                  background: "rgba(251,191,36,0.16)",
                  border: "1px solid rgba(251,191,36,0.35)",
                  color: "#e5e7eb",
                  fontSize: 13,
                  fontWeight: 700,
                }}
              >
                AI marketing tools
              </div>
            </div>
          </div>

          <div
            style={{
              background: "rgba(255,255,255,0.94)",
              borderRadius: 24,
              padding: 22,
              boxShadow: "0 20px 60px rgba(10, 14, 30, 0.22)",
            }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}>
              <div>
                <div style={{ fontWeight: 900, fontSize: 26 }}>Tradesman AI</div>
                <div style={{ color: "#4b5563", marginTop: 4 }}>
                  {session?.user?.email
                    ? `Signed in as ${session.user.email} • ${plan.toUpperCase()}`
                    : `3 free public estimates before upgrade`}
                </div>
              </div>

              {session ? (
                <button onClick={handleSignOut} style={secondaryButtonStyle}>
                  Sign Out
                </button>
              ) : null}
            </div>

            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(3, 1fr)",
                gap: 12,
                marginTop: 18,
              }}
            >
              <div
                style={{
                  border: "1px solid #e5e7eb",
                  borderRadius: 12,
                  padding: 16,
                  background: "#ffffff",
                }}
              >
                <div style={{ fontWeight: 800, fontSize: 18 }}>Basic</div>
                <div style={{ fontSize: 24, fontWeight: 800, margin: "8px 0 12px" }}>$19/mo</div>
                <ul style={{ paddingLeft: 18, marginBottom: 12 }}>
                  <li>Unlimited estimates</li>
                  <li>Company pricing settings</li>
                  <li>Translation tools</li>
                  <li>Core workflow</li>
                </ul>
                <button
                  onClick={() => window.open(BASIC_STRIPE_LINK, "_blank")}
                  style={primaryButtonStyle}
                >
                  Choose Basic
                </button>
              </div>

              <div
                style={{
                  border: "2px solid #6366f1",
                  borderRadius: 12,
                  padding: 16,
                  background: "#eef2ff",
                }}
              >
                <div style={{ fontWeight: 800, fontSize: 18 }}>Pro</div>
                <div style={{ fontSize: 24, fontWeight: 800, margin: "8px 0 12px" }}>$49/mo</div>
                <ul style={{ paddingLeft: 18, marginBottom: 12 }}>
                  <li>Everything in Basic</li>
                  <li>Lead inbox</li>
                  <li>AI replies</li>
                  <li>Marketing generator</li>
                </ul>
                <button
                  onClick={() => window.open(PRO_STRIPE_LINK, "_blank")}
                  style={primaryButtonStyle}
                >
                  Choose Pro
                </button>
              </div>

              <div
                style={{
                  border: "1px solid #e5e7eb",
                  borderRadius: 12,
                  padding: 16,
                  background: "#ffffff",
                }}
              >
                <div style={{ fontWeight: 800, fontSize: 18 }}>Team</div>
                <div style={{ fontSize: 24, fontWeight: 800, margin: "8px 0 12px" }}>$99/mo</div>
                <ul style={{ paddingLeft: 18, marginBottom: 12 }}>
                  <li>Everything in Pro</li>
                  <li>Shared office use</li>
                  <li>Team positioning</li>
                  <li>Priority support</li>
                </ul>
                <button
                  onClick={() => window.open(TEAM_STRIPE_LINK, "_blank")}
                  style={primaryButtonStyle}
                >
                  Choose Team
                </button>
              </div>
            </div>

            {!session && (
              <div
                style={{
                  marginTop: 16,
                  padding: 14,
                  borderRadius: 14,
                  background: "#eef2ff",
                  border: "1px solid #c7d2fe",
                  fontWeight: 700,
                  color: "#3730a3",
                }}
              >
                Free estimates used: {freeEstimateUses} / 3
              </div>
            )}
          </div>
        </div>

        {!session && (
          <div
            style={{
              background: "rgba(255,255,255,0.95)",
              borderRadius: 20,
              padding: 22,
              marginBottom: 24,
              boxShadow: "0 16px 40px rgba(10, 14, 30, 0.16)",
            }}
          >
            <h2 style={{ marginTop: 0 }}>
              {authMode === "signin" ? "Sign In" : "Create Account"}
            </h2>

            <div style={{ display: "flex", gap: 10, marginBottom: 16 }}>
              <button
                onClick={() => setAuthMode("signin")}
                style={authMode === "signin" ? primaryButtonStyle : secondaryButtonStyle}
              >
                Sign In
              </button>
              <button
                onClick={() => setAuthMode("signup")}
                style={authMode === "signup" ? primaryButtonStyle : secondaryButtonStyle}
              >
                Sign Up
              </button>
            </div>

            <div style={{ display: "grid", gap: 12, maxWidth: 480 }}>
              <input
                type="email"
                placeholder="Email"
                value={authEmail}
                onChange={(e) => setAuthEmail(e.target.value)}
                style={inputStyle}
              />
              <input
                type="password"
                placeholder="Password"
                value={authPassword}
                onChange={(e) => setAuthPassword(e.target.value)}
                style={inputStyle}
              />
              {authMode === "signin" ? (
                <button onClick={handleSignIn} style={primaryButtonStyle}>
                  Sign In
                </button>
              ) : (
                <button onClick={handleSignUp} style={primaryButtonStyle}>
                  Create Account
                </button>
              )}
            </div>

            <div style={{ marginTop: 12, color: "#6b7280" }}>{authMessage}</div>
          </div>
        )}

        {session && (
          <div
            style={{
              background: "rgba(255,255,255,0.95)",
              borderRadius: 20,
              padding: 18,
              marginBottom: 24,
              boxShadow: "0 16px 40px rgba(10, 14, 30, 0.16)",
            }}
          >
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
              <button onClick={() => setPlan("basic")} style={secondaryButtonStyle}>
                Set Basic
              </button>
              <button onClick={() => setPlan("pro")} style={secondaryButtonStyle}>
                Set Pro
              </button>
              <button onClick={() => setPlan("team")} style={secondaryButtonStyle}>
                Set Team
              </button>
            </div>
          </div>
        )}

        <div
          style={{
            background: "rgba(255,255,255,0.96)",
            borderRadius: 20,
            padding: 22,
            marginBottom: 24,
            boxShadow: "0 16px 40px rgba(10, 14, 30, 0.16)",
          }}
        >
          <h2 style={{ marginTop: 0 }}>Instant Estimate Tool</h2>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr 1fr",
              gap: 12,
              marginBottom: 14,
            }}
          >
            <input
              value={companyName}
              onChange={(e) => setCompanyName(e.target.value)}
              placeholder="Company Name"
              style={inputStyle}
            />
            <input
              type="number"
              value={laborRateSetting}
              onChange={(e) => setLaborRateSetting(Number(e.target.value))}
              placeholder="Labor Rate"
              style={inputStyle}
            />
            <input
              type="number"
              value={markupSetting}
              onChange={(e) => setMarkupSetting(Number(e.target.value))}
              placeholder="Markup %"
              style={inputStyle}
            />
          </div>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1.3fr 0.35fr 0.35fr",
              gap: 12,
              marginBottom: 14,
            }}
          >
            <textarea
              value={jobDescription}
              onChange={(e) => setJobDescription(e.target.value)}
              placeholder="Type the job in plain English. Example: gravel driveway 200x40 with grading and base material"
              style={{
                minHeight: 120,
                padding: 12,
                borderRadius: 12,
                border: "1px solid #d1d5db",
                resize: "vertical",
              }}
            />
            <select
              value={language}
              onChange={(e) => setLanguage(e.target.value as Language)}
              style={{
                padding: 12,
                borderRadius: 12,
                border: "1px solid #d1d5db",
                height: 48,
              }}
            >
              {LANGUAGES.map((lang) => (
                <option key={lang} value={lang}>
                  {lang}
                </option>
              ))}
            </select>
            <button onClick={generateFrontDoorEstimate} style={primaryButtonStyle}>
              Generate Estimate
            </button>
          </div>

          {!session && freeEstimateUses >= 3 && (
            <div
              style={{
                background: "#fff7ed",
                border: "1px solid #fdba74",
                borderRadius: 12,
                padding: 12,
                marginBottom: 14,
                color: "#9a3412",
                fontWeight: 700,
              }}
            >
              You used your 3 free estimates. Upgrade to continue with unlimited estimates, lead tools, and AI marketing.
            </div>
          )}

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr",
              gap: 16,
            }}
          >
            <div
              style={{
                background: "linear-gradient(180deg, #eff6ff 0%, #f8fafc 100%)",
                border: "1px solid #dbeafe",
                borderRadius: 16,
                padding: 16,
              }}
            >
              <strong>Live Estimate Snapshot</strong>
              <div style={{ marginTop: 10, lineHeight: 1.85 }}>
                <div>Job Type: {liveEstimate.jobType}</div>
                <div>Labor Hours: {liveEstimate.laborHours}</div>
                <div>Labor Rate: {money(liveEstimate.laborRate)}</div>
                <div>Labor Cost: {money(liveEstimate.laborCost)}</div>
                <div>Materials Cost: {money(liveEstimate.materialsCost)}</div>
                <div>Equipment Cost: {money(liveEstimate.equipmentCost)}</div>
                <div>Markup: {liveEstimate.markupPercent}%</div>
                <div><strong>Total: {money(liveEstimate.total)}</strong></div>
              </div>
            </div>

            <div
              style={{
                background: "linear-gradient(180deg, #faf5ff 0%, #f8fafc 100%)",
                border: "1px solid #e9d5ff",
                borderRadius: 16,
                padding: 16,
              }}
            >
              <strong>What this becomes</strong>
              <div style={{ marginTop: 10, lineHeight: 1.85, color: "#374151" }}>
                <div>• instant estimate for the customer</div>
                <div>• faster first response</div>
                <div>• cleaner quote flow</div>
                <div>• upsell into inbox assistant and marketing</div>
              </div>
            </div>
          </div>
        </div>

        <div
          style={{
            background: "rgba(255,255,255,0.96)",
            borderRadius: 20,
            padding: 22,
            marginBottom: 24,
            boxShadow: "0 16px 40px rgba(10, 14, 30, 0.16)",
            opacity: hasAccess(plan, "pro") ? 1 : 0.96,
          }}
        >
          <h2 style={{ marginTop: 0 }}>Contractor Inbox Assistant</h2>
          <p style={{ color: "#4b5563", marginTop: -2 }}>
            Score the lead, generate the quote range, build the first reply, and tee up the follow-up.
          </p>

          {!hasAccess(plan, "pro") && (
            <div
              style={{
                background: "#fff7ed",
                border: "1px solid #fdba74",
                borderRadius: 12,
                padding: 12,
                marginBottom: 14,
                color: "#9a3412",
                fontWeight: 700,
              }}
            >
              Pro or Team unlocks the full lead inbox workflow and saved leads.
            </div>
          )}

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr",
              gap: 12,
              marginBottom: 12,
            }}
          >
            <input
              value={leadTitle}
              onChange={(e) => setLeadTitle(e.target.value)}
              placeholder="Lead title"
              style={inputStyle}
            />
            <input
              value={leadCity}
              onChange={(e) => setLeadCity(e.target.value)}
              placeholder="City"
              style={inputStyle}
            />
          </div>

          <textarea
            value={leadDescription}
            onChange={(e) => setLeadDescription(e.target.value)}
            placeholder="Paste the incoming lead or job request here."
            style={{
              width: "100%",
              minHeight: 120,
              padding: 12,
              borderRadius: 12,
              border: "1px solid #d1d5db",
              resize: "vertical",
              boxSizing: "border-box",
              marginBottom: 12,
            }}
          />

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr 1fr",
              gap: 12,
              marginBottom: 14,
            }}
          >
            <input
              value={leadContactName}
              onChange={(e) => setLeadContactName(e.target.value)}
              placeholder="Contact name"
              style={inputStyle}
            />
            <input
              value={leadContactInfo}
              onChange={(e) => setLeadContactInfo(e.target.value)}
              placeholder="Phone or email"
              style={inputStyle}
            />
            <input
              value={leadBudget}
              onChange={(e) => setLeadBudget(e.target.value)}
              placeholder="Budget"
              style={inputStyle}
            />
          </div>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(4, 1fr)",
              gap: 12,
              marginBottom: 16,
            }}
          >
            <div style={{ background: "#f8fafc", border: "1px solid #e5e7eb", borderRadius: 12, padding: 14 }}>
              <div style={{ fontSize: 12, color: "#6b7280" }}>Lead Score</div>
              <div style={{ fontSize: 22, fontWeight: 800 }}>{inboxAssistant.score}</div>
            </div>
            <div style={{ background: "#f8fafc", border: "1px solid #e5e7eb", borderRadius: 12, padding: 14 }}>
              <div style={{ fontSize: 12, color: "#6b7280" }}>Heat Bucket</div>
              <div style={{ fontSize: 22, fontWeight: 800 }}>{inboxAssistant.bucket}</div>
            </div>
            <div style={{ background: "#f8fafc", border: "1px solid #e5e7eb", borderRadius: 12, padding: 14 }}>
              <div style={{ fontSize: 12, color: "#6b7280" }}>Job Type</div>
              <div style={{ fontSize: 22, fontWeight: 800 }}>{inboxAssistant.jobType}</div>
            </div>
            <div style={{ background: "#f8fafc", border: "1px solid #e5e7eb", borderRadius: 12, padding: 14 }}>
              <div style={{ fontSize: 12, color: "#6b7280" }}>Quote Range</div>
              <div style={{ fontSize: 22, fontWeight: 800 }}>{inboxAssistant.range}</div>
            </div>
          </div>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr 1fr",
              gap: 16,
            }}
          >
            <div
              style={{
                border: "1px solid #e5e7eb",
                borderRadius: 16,
                padding: 16,
                background: "#f8fafc",
              }}
            >
              <div style={{ fontWeight: 800, marginBottom: 8 }}>Quick Reply</div>
              <div style={{ whiteSpace: "pre-wrap", lineHeight: 1.7 }}>
                {inboxAssistant.quickReply}
              </div>
              <div style={{ marginTop: 12 }}>
                <button onClick={() => setOutput(inboxAssistant.quickReply)} style={secondaryButtonStyle}>
                  Load Reply
                </button>
              </div>
            </div>

            <div
              style={{
                border: "1px solid #e5e7eb",
                borderRadius: 16,
                padding: 16,
                background: "#f8fafc",
              }}
            >
              <div style={{ fontWeight: 800, marginBottom: 8 }}>Follow-Up</div>
              <div style={{ whiteSpace: "pre-wrap", lineHeight: 1.7 }}>
                {inboxAssistant.followUp}
              </div>
              <div style={{ marginTop: 12 }}>
                <button onClick={() => setOutput(inboxAssistant.followUp)} style={secondaryButtonStyle}>
                  Load Follow-Up
                </button>
              </div>
            </div>

            <div
              style={{
                border: "1px solid #e5e7eb",
                borderRadius: 16,
                padding: 16,
                background: "#f8fafc",
              }}
            >
              <div style={{ fontWeight: 800, marginBottom: 8 }}>Close Angle</div>
              <div style={{ lineHeight: 1.7, marginBottom: 10 }}>
                {inboxAssistant.closeAngle}
              </div>
              <div style={{ fontWeight: 700, marginBottom: 6 }}>Why it scored this way</div>
              <div style={{ lineHeight: 1.7 }}>
                {inboxAssistant.reasons.length
                  ? inboxAssistant.reasons.join(" • ")
                  : "No strong signals found yet."}
              </div>
            </div>
          </div>

          <div style={{ marginTop: 14, display: "flex", gap: 10, flexWrap: "wrap" }}>
            <button onClick={() => setOutput(inboxAssistant.quickReply)} style={primaryButtonStyle}>
              Use Quick Reply
            </button>
            <button onClick={() => setOutput(inboxAssistant.followUp)} style={secondaryButtonStyle}>
              Use Follow-Up
            </button>
            <button
              onClick={() => setOutput(`Suggested quote range: ${inboxAssistant.range}`)}
              style={secondaryButtonStyle}
            >
              Load Quote Range
            </button>
            {session && hasAccess(plan, "pro") && (
              <button onClick={() => void addLead()} style={primaryButtonStyle}>
                Save Lead
              </button>
            )}
          </div>
        </div>

        {session && (
          <div
            style={{
              background: "rgba(255,255,255,0.96)",
              borderRadius: 20,
              padding: 22,
              marginBottom: 24,
              boxShadow: "0 16px 40px rgba(10, 14, 30, 0.16)",
            }}
          >
            <h2 style={{ marginTop: 0 }}>Customer Manager</h2>

            <div style={{ display: "flex", gap: 10, marginBottom: 14 }}>
              <input
                value={customerName}
                onChange={(e) => setCustomerName(e.target.value)}
                placeholder="Customer Name"
                style={{ ...inputStyle, flex: 1 }}
              />
              <button onClick={addCustomer} style={primaryButtonStyle}>
                Add
              </button>
            </div>

            <select
              value={selectedCustomer}
              onChange={(e) => setSelectedCustomer(e.target.value)}
              style={{
                width: "100%",
                padding: 12,
                borderRadius: 12,
                border: "1px solid #d1d5db",
                marginBottom: 16,
              }}
            >
              <option value="">Select Customer</option>
              {customers.map((c, i) => (
                <option key={`${c.name}-${i}`} value={c.name}>
                  {c.name}
                </option>
              ))}
            </select>

            <div style={{ maxHeight: 220, overflowY: "auto" }}>
              {customers.length === 0 ? (
                <div style={{ color: "#6b7280" }}>No customers yet.</div>
              ) : (
                customers.map((c, i) => (
                  <div
                    key={`${c.name}-${i}`}
                    style={{
                      padding: "10px 0",
                      borderBottom: "1px solid #f1f5f9",
                    }}
                  >
                    <strong>{c.name}</strong>
                    <div style={{ fontSize: 12, color: "#6b7280" }}>
                      Added {c.created}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        )}

        <div
          style={{
            background: "rgba(255,255,255,0.96)",
            borderRadius: 20,
            padding: 22,
            marginBottom: 24,
            boxShadow: "0 16px 40px rgba(10, 14, 30, 0.16)",
          }}
        >
          <h2 style={{ marginTop: 0 }}>Language + Output Tools</h2>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "0.4fr 1fr",
              gap: 12,
              alignItems: "center",
              marginBottom: 12,
            }}
          >
            <select
              value={translateLanguage}
              onChange={(e) => setTranslateLanguage(e.target.value as Language)}
              style={{
                padding: 12,
                borderRadius: 12,
                border: "1px solid #d1d5db",
              }}
            >
              {LANGUAGES.map((lang) => (
                <option key={lang} value={lang}>
                  Translate to {lang}
                </option>
              ))}
            </select>

            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
              <button onClick={translateFullOutput} style={primaryButtonStyle}>
                Translate Full Output
              </button>
              <button onClick={translateSelectedText} style={primaryButtonStyle}>
                Translate Selected Text
              </button>
              <button onClick={copyOutput} style={secondaryButtonStyle}>
                Copy Output
              </button>
            </div>
          </div>

          <textarea
            ref={outputRef}
            value={output}
            onChange={(e) => setOutput(e.target.value)}
            onSelect={handleSelection}
            placeholder="Generated estimate, quick reply, follow-up, or translated output will appear here..."
            style={{
              width: "100%",
              minHeight: 320,
              padding: 14,
              borderRadius: 12,
              border: "1px solid #d1d5db",
              resize: "vertical",
              boxSizing: "border-box",
              marginBottom: 14,
            }}
          />

          <div
            style={{
              background: "#f8fafc",
              border: "1px solid #e5e7eb",
              borderRadius: 12,
              padding: 14,
            }}
          >
            <div style={{ fontWeight: 700, marginBottom: 8 }}>Translation Preview</div>
            <div
              style={{
                minHeight: 80,
                whiteSpace: "pre-wrap",
                color: translationPreview ? "#111827" : "#6b7280",
                marginBottom: 12,
              }}
            >
              {translationPreview || "Translated text preview will appear here."}
            </div>

            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
              <button onClick={replaceAllWithTranslatedPreview} style={primaryButtonStyle}>
                Replace Output With Preview
              </button>
              <button
                onClick={() => navigator.clipboard.writeText(translationPreview)}
                style={secondaryButtonStyle}
              >
                Copy Preview
              </button>
            </div>
          </div>
        </div>

        <div
          style={{
            background: "rgba(255,255,255,0.96)",
            borderRadius: 20,
            padding: 22,
            marginBottom: 24,
            boxShadow: "0 16px 40px rgba(10, 14, 30, 0.16)",
            opacity: hasAccess(plan, "pro") ? 1 : 0.96,
          }}
        >
          <h2 style={{ marginTop: 0 }}>Saved Lead Inbox (Pro+)</h2>

          {!hasAccess(plan, "pro") && (
            <div
              style={{
                background: "#fff7ed",
                border: "1px solid #fdba74",
                borderRadius: 12,
                padding: 12,
                marginBottom: 14,
                color: "#9a3412",
                fontWeight: 700,
              }}
            >
              Upgrade to Pro or Team to save leads, track pipeline status, and use the inbox assistant as an operating system.
            </div>
          )}

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(4, 1fr)",
              gap: 12,
              marginBottom: 16,
            }}
          >
            <div style={{ background: "#f8fafc", border: "1px solid #e5e7eb", borderRadius: 12, padding: 14 }}>
              <div style={{ fontSize: 12, color: "#6b7280" }}>Total Leads</div>
              <div style={{ fontSize: 22, fontWeight: 800 }}>{leadStats.total}</div>
            </div>
            <div style={{ background: "#f8fafc", border: "1px solid #e5e7eb", borderRadius: 12, padding: 14 }}>
              <div style={{ fontSize: 12, color: "#6b7280" }}>Hot Leads</div>
              <div style={{ fontSize: 22, fontWeight: 800 }}>{leadStats.hot}</div>
            </div>
            <div style={{ background: "#f8fafc", border: "1px solid #e5e7eb", borderRadius: 12, padding: 14 }}>
              <div style={{ fontSize: 12, color: "#6b7280" }}>Quoted</div>
              <div style={{ fontSize: 22, fontWeight: 800 }}>{leadStats.quoted}</div>
            </div>
            <div style={{ background: "#f8fafc", border: "1px solid #e5e7eb", borderRadius: 12, padding: 14 }}>
              <div style={{ fontSize: 12, color: "#6b7280" }}>Won</div>
              <div style={{ fontSize: 22, fontWeight: 800 }}>{leadStats.won}</div>
            </div>
          </div>

          <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 18 }}>
            <select
              value={leadStatusFilter}
              onChange={(e) => setLeadStatusFilter(e.target.value)}
              style={{
                padding: 12,
                borderRadius: 10,
                border: "1px solid #d1d5db",
              }}
            >
              <option value="all">All statuses</option>
              <option value="new">New</option>
              <option value="contacted">Contacted</option>
              <option value="quoted">Quoted</option>
              <option value="won">Won</option>
            </select>

            <select
              value={leadBucketFilter}
              onChange={(e) => setLeadBucketFilter(e.target.value)}
              style={{
                padding: 12,
                borderRadius: 10,
                border: "1px solid #d1d5db",
              }}
            >
              <option value="all">All buckets</option>
              <option value="Hot">Hot</option>
              <option value="Warm">Warm</option>
              <option value="Cold">Cold</option>
            </select>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 16 }}>
            <div style={{ background: "#fff1f2", borderRadius: 12, padding: 14, border: "1px solid #e5e7eb" }}>
              <div style={{ fontWeight: 800, marginBottom: 10 }}>{`Hot 🔥 (${hotLeads.length})`}</div>
              {hotLeads.length === 0 && <div style={{ color: "#6b7280" }}>No leads</div>}
              {hotLeads.map((lead) => (
                <div
                  key={lead.id}
                  style={{
                    border: "1px solid #e5e7eb",
                    borderRadius: 12,
                    padding: 12,
                    background: "#fff",
                    marginBottom: 12,
                  }}
                >
                  <div style={{ fontWeight: 800 }}>{lead.title || "Untitled Lead"}</div>
                  <div style={{ color: "#6b7280", fontSize: 13, marginBottom: 8 }}>
                    {lead.city || "No city"} • {lead.created_at}
                  </div>
                  <div style={{ whiteSpace: "pre-wrap", marginBottom: 8 }}>{lead.description || "No description"}</div>
                  <div style={{ fontSize: 14, lineHeight: 1.7 }}>
                    <div>Status: <strong>{lead.status}</strong></div>
                    <div>Score: <strong>{lead.score}</strong></div>
                    <div>Contact: {lead.contact_name || "-"} / {lead.contact_info || "-"}</div>
                  </div>
                  <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}>
                    <button onClick={() => setOutput(buildContractorInboxAssistant({
                      title: lead.title,
                      description: lead.description,
                      city: lead.city,
                      contactName: lead.contact_name,
                      contactInfo: lead.contact_info,
                      budget: lead.budget,
                    }, laborRateSetting, markupSetting).quickReply)} style={secondaryButtonStyle}>
                      Load Reply
                    </button>
                    <button onClick={() => updateLeadStatus(lead.id, "quoted")} style={secondaryButtonStyle}>
                      Quoted
                    </button>
                    <button onClick={() => updateLeadStatus(lead.id, "won")} style={secondaryButtonStyle}>
                      Won
                    </button>
                    <button onClick={() => deleteLead(lead.id)} style={secondaryButtonStyle}>
                      Delete
                    </button>
                  </div>
                </div>
              ))}
            </div>

            <div style={{ background: "#fffbeb", borderRadius: 12, padding: 14, border: "1px solid #e5e7eb" }}>
              <div style={{ fontWeight: 800, marginBottom: 10 }}>{`Warm (${warmLeads.length})`}</div>
              {warmLeads.length === 0 && <div style={{ color: "#6b7280" }}>No leads</div>}
              {warmLeads.map((lead) => (
                <div
                  key={lead.id}
                  style={{
                    border: "1px solid #e5e7eb",
                    borderRadius: 12,
                    padding: 12,
                    background: "#fff",
                    marginBottom: 12,
                  }}
                >
                  <div style={{ fontWeight: 800 }}>{lead.title || "Untitled Lead"}</div>
                  <div style={{ color: "#6b7280", fontSize: 13, marginBottom: 8 }}>
                    {lead.city || "No city"} • {lead.created_at}
                  </div>
                  <div style={{ whiteSpace: "pre-wrap", marginBottom: 8 }}>{lead.description || "No description"}</div>
                  <div style={{ fontSize: 14, lineHeight: 1.7 }}>
                    <div>Status: <strong>{lead.status}</strong></div>
                    <div>Score: <strong>{lead.score}</strong></div>
                    <div>Contact: {lead.contact_name || "-"} / {lead.contact_info || "-"}</div>
                  </div>
                  <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}>
                    <button onClick={() => setOutput(buildContractorInboxAssistant({
                      title: lead.title,
                      description: lead.description,
                      city: lead.city,
                      contactName: lead.contact_name,
                      contactInfo: lead.contact_info,
                      budget: lead.budget,
                    }, laborRateSetting, markupSetting).quickReply)} style={secondaryButtonStyle}>
                      Load Reply
                    </button>
                    <button onClick={() => updateLeadStatus(lead.id, "contacted")} style={secondaryButtonStyle}>
                      Contacted
                    </button>
                    <button onClick={() => updateLeadStatus(lead.id, "quoted")} style={secondaryButtonStyle}>
                      Quoted
                    </button>
                    <button onClick={() => deleteLead(lead.id)} style={secondaryButtonStyle}>
                      Delete
                    </button>
                  </div>
                </div>
              ))}
            </div>

            <div style={{ background: "#f8fafc", borderRadius: 12, padding: 14, border: "1px solid #e5e7eb" }}>
              <div style={{ fontWeight: 800, marginBottom: 10 }}>{`Cold (${coldLeads.length})`}</div>
              {coldLeads.length === 0 && <div style={{ color: "#6b7280" }}>No leads</div>}
              {coldLeads.map((lead) => (
                <div
                  key={lead.id}
                  style={{
                    border: "1px solid #e5e7eb",
                    borderRadius: 12,
                    padding: 12,
                    background: "#fff",
                    marginBottom: 12,
                  }}
                >
                  <div style={{ fontWeight: 800 }}>{lead.title || "Untitled Lead"}</div>
                  <div style={{ color: "#6b7280", fontSize: 13, marginBottom: 8 }}>
                    {lead.city || "No city"} • {lead.created_at}
                  </div>
                  <div style={{ whiteSpace: "pre-wrap", marginBottom: 8 }}>{lead.description || "No description"}</div>
                  <div style={{ fontSize: 14, lineHeight: 1.7 }}>
                    <div>Status: <strong>{lead.status}</strong></div>
                    <div>Score: <strong>{lead.score}</strong></div>
                    <div>Contact: {lead.contact_name || "-"} / {lead.contact_info || "-"}</div>
                  </div>
                  <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}>
                    <button onClick={() => setOutput(buildContractorInboxAssistant({
                      title: lead.title,
                      description: lead.description,
                      city: lead.city,
                      contactName: lead.contact_name,
                      contactInfo: lead.contact_info,
                      budget: lead.budget,
                    }, laborRateSetting, markupSetting).followUp)} style={secondaryButtonStyle}>
                      Load Follow-Up
                    </button>
                    <button onClick={() => updateLeadStatus(lead.id, "contacted")} style={secondaryButtonStyle}>
                      Contacted
                    </button>
                    <button onClick={() => deleteLead(lead.id)} style={secondaryButtonStyle}>
                      Delete
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div
          style={{
            background: "rgba(255,255,255,0.96)",
            borderRadius: 20,
            padding: 22,
            marginBottom: 24,
            boxShadow: "0 16px 40px rgba(10, 14, 30, 0.16)",
            opacity: hasAccess(plan, "pro") ? 1 : 0.96,
          }}
        >
          <h2 style={{ marginTop: 0 }}>AI Marketing Generator (Pro+)</h2>

          {!hasAccess(plan, "pro") && (
            <div
              style={{
                background: "#fff7ed",
                border: "1px solid #fdba74",
                borderRadius: 12,
                padding: 12,
                marginBottom: 14,
                color: "#9a3412",
                fontWeight: 700,
              }}
            >
              Upgrade to Pro or Team to generate ads, hooks, offers, and social posts.
            </div>
          )}

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr auto",
              gap: 12,
              marginBottom: 12,
            }}
          >
            <input
              value={marketingJob}
              onChange={(e) => setMarketingJob(e.target.value)}
              placeholder="Service type (example: gravel driveway)"
              style={inputStyle}
            />
            <input
              value={marketingCity}
              onChange={(e) => setMarketingCity(e.target.value)}
              placeholder="City"
              style={inputStyle}
            />
            <button onClick={buildMarketing} style={primaryButtonStyle}>
              Generate
            </button>
          </div>

          <textarea
            value={marketingOutput}
            onChange={(e) => setMarketingOutput(e.target.value)}
            style={{
              width: "100%",
              minHeight: 220,
              padding: 12,
              borderRadius: 12,
              border: "1px solid #d1d5db",
              boxSizing: "border-box",
            }}
            placeholder="Generated marketing content will appear here..."
          />
        </div>
      </div>
    </div>
  );
}