import React, { useEffect, useMemo, useRef, useState } from "react";
import { scoreLead, scoreBucket } from "./leadEngine";

type Language = "English" | "Spanish" | "French" | "German" | "Portuguese";

type Customer = {
  name: string;
  created: string;
};

type LeadRow = {
  id: string;
  title: string;
  description: string;
  city: string;
  source: string;
  contact_name: string;
  contact_info: string;
  budget: string;
  score: number;
  status: string;
  created_at: string;
};

type EstimateData = {
  jobType: string;
  laborHours: number;
  laborRate: number;
  laborCost: number;
  materialsCost: number;
  equipmentCost: number;
  subtotal: number;
  markupPercent: number;
  markupAmount: number;
  total: number;
  scope: string;
  recommendations: string[];
};

const BASIC_STRIPE_LINK = "https://buy.stripe.com/eVqdR26372Cb7BW8Y5d7q03";
const PRO_STRIPE_LINK = "https://buy.stripe.com/dRmfZa3UZa4D7BWgqxd7q04";

const SUPABASE_URL = "https://ljizlaabarhyzocfcsba.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqaXpsYWFiYXJoeXpvY2Zjc2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1ODcxNTIsImV4cCI6MjA4OTE2MzE1Mn0.eJstZOcLE_BALH1JMhju4zQonRxMQwk5DbEXpYUIKbw";

const supabase = (window as any).supabase.createClient(
  SUPABASE_URL,
  SUPABASE_ANON_KEY
);

const LANGUAGES: Language[] = [
  "English",
  "Spanish",
  "French",
  "German",
  "Portuguese",
];

const languageLabels: Record<
  Language,
  {
    estimateTitle: string;
    estimateFor: string;
    customer: string;
    jobDescription: string;
    detectedJobType: string;
    scopeOfWork: string;
    laborHours: string;
    laborRate: string;
    laborCost: string;
    materialsCost: string;
    equipmentCost: string;
    subtotal: string;
    markup: string;
    totalEstimate: string;
    recommendations: string;
    generatedBy: string;
    currencyNote: string;
  }
> = {
  English: {
    estimateTitle: "PROFESSIONAL ESTIMATE",
    estimateFor: "Estimate For",
    customer: "Customer",
    jobDescription: "Job Description",
    detectedJobType: "Detected Job Type",
    scopeOfWork: "Scope of Work",
    laborHours: "Estimated Labor Hours",
    laborRate: "Labor Rate",
    laborCost: "Labor Cost",
    materialsCost: "Materials Cost",
    equipmentCost: "Equipment Cost",
    subtotal: "Subtotal",
    markup: "Markup",
    totalEstimate: "Total Estimate",
    recommendations: "Recommendations",
    generatedBy: "Generated by Tradesman AI",
    currencyNote:
      "All pricing is an estimate and should be reviewed before sending.",
  },
  Spanish: {
    estimateTitle: "PRESUPUESTO PROFESIONAL",
    estimateFor: "Presupuesto Para",
    customer: "Cliente",
    jobDescription: "Descripción del Trabajo",
    detectedJobType: "Tipo de Trabajo Detectado",
    scopeOfWork: "Alcance del Trabajo",
    laborHours: "Horas de Mano de Obra Estimadas",
    laborRate: "Tarifa de Mano de Obra",
    laborCost: "Costo de Mano de Obra",
    materialsCost: "Costo de Materiales",
    equipmentCost: "Costo de Equipo",
    subtotal: "Subtotal",
    markup: "Margen",
    totalEstimate: "Presupuesto Total",
    recommendations: "Recomendaciones",
    generatedBy: "Generado por Tradesman AI",
    currencyNote:
      "Todos los precios son estimados y deben revisarse antes de enviarlos.",
  },
  French: {
    estimateTitle: "DEVIS PROFESSIONNEL",
    estimateFor: "Devis Pour",
    customer: "Client",
    jobDescription: "Description du Travail",
    detectedJobType: "Type de Travail Détecté",
    scopeOfWork: "Étendue des Travaux",
    laborHours: "Heures de Main-d'œuvre Estimées",
    laborRate: "Taux de Main-d'œuvre",
    laborCost: "Coût de Main-d'œuvre",
    materialsCost: "Coût des Matériaux",
    equipmentCost: "Coût de l'Équipement",
    subtotal: "Sous-total",
    markup: "Marge",
    totalEstimate: "Devis Total",
    recommendations: "Recommandations",
    generatedBy: "Généré par Tradesman AI",
    currencyNote:
      "Tous les prix sont estimatifs et doivent être vérifiés avant envoi.",
  },
  German: {
    estimateTitle: "PROFESSIONELLES ANGEBOT",
    estimateFor: "Angebot Für",
    customer: "Kunde",
    jobDescription: "Arbeitsbeschreibung",
    detectedJobType: "Erkannter Arbeitstyp",
    scopeOfWork: "Leistungsumfang",
    laborHours: "Geschätzte Arbeitsstunden",
    laborRate: "Stundensatz",
    laborCost: "Arbeitskosten",
    materialsCost: "Materialkosten",
    equipmentCost: "Gerätekosten",
    subtotal: "Zwischensumme",
    markup: "Aufschlag",
    totalEstimate: "Gesamtangebot",
    recommendations: "Empfehlungen",
    generatedBy: "Erstellt von Tradesman AI",
    currencyNote:
      "Alle Preise sind Schätzungen und sollten vor dem Versand geprüft werden.",
  },
  Portuguese: {
    estimateTitle: "ORÇAMENTO PROFISSIONAL",
    estimateFor: "Orçamento Para",
    customer: "Cliente",
    jobDescription: "Descrição do Serviço",
    detectedJobType: "Tipo de Serviço Detectado",
    scopeOfWork: "Escopo do Trabalho",
    laborHours: "Horas de Mão de Obra Estimadas",
    laborRate: "Taxa de Mão de Obra",
    laborCost: "Custo de Mão de Obra",
    materialsCost: "Custo de Materiais",
    equipmentCost: "Custo de Equipamento",
    subtotal: "Subtotal",
    markup: "Margem",
    totalEstimate: "Orçamento Total",
    recommendations: "Recomendações",
    generatedBy: "Gerado por Tradesman AI",
    currencyNote:
      "Todos os preços são estimados e devem ser revisados antes do envio.",
  },
};

function money(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 2,
  }).format(value);
}

function detectJobType(description: string): string {
  const text = description.toLowerCase();
  if (text.includes("fence")) return "Fence Work";
  if (text.includes("gravel") || text.includes("road base")) return "Gravel / Base Work";
  if (text.includes("driveway")) return "Driveway Work";
  if (text.includes("pad")) return "Pad Prep";
  if (text.includes("brush") || text.includes("clear")) return "Brush Clearing";
  if (text.includes("concrete")) return "Concrete Work";
  if (text.includes("demo") || text.includes("demolition") || text.includes("remove")) {
    return "Demolition / Removal";
  }
  if (text.includes("excavat") || text.includes("dig") || text.includes("trench")) {
    return "Excavation";
  }
  if (text.includes("alternator") || text.includes("repair") || text.includes("mechanic")) {
    return "Mechanical Repair";
  }
  return "General Contract Work";
}

function parseDimensionMultiplier(description: string): number {
  const match = description.match(/(\d+)\s*x\s*(\d+)/i);
  if (!match) return 1;

  const a = Number(match[1]);
  const b = Number(match[2]);
  if (!Number.isFinite(a) || !Number.isFinite(b)) return 1;

  const area = a * b;
  if (area <= 400) return 1;
  if (area <= 1200) return 1.35;
  if (area <= 2500) return 1.75;
  return 2.2;
}

function generateEstimateData(description: string): EstimateData {
  const text = description.toLowerCase().trim();
  const jobType = detectJobType(description);
  const sizeMultiplier = parseDimensionMultiplier(description);

  let laborHours = 6;
  let laborRate = 95;
  let materialsCost = 250;
  let equipmentCost = 200;
  const markupPercent = 18;
  let scope =
    "Provide labor, tools, equipment, setup, cleanup, and standard job completion based on the described work.";

  const recommendations: string[] = [];

  if (text.includes("gravel") || text.includes("road base")) {
    laborHours = 10;
    materialsCost = 1200;
    equipmentCost = 550;
    scope =
      "Supply, spread, grade, and compact gravel or base material to the requested area.";
    recommendations.push("Verify haul distance and material availability.");
    recommendations.push("Confirm final grade and compaction requirements.");
  }

  if (text.includes("driveway")) {
    laborHours = 12;
    materialsCost += 900;
    equipmentCost += 400;
    scope =
      "Prepare driveway area, place material, grade surface, and leave site ready for use.";
    recommendations.push("Measure actual driveway length and width before final quote.");
  }

  if (text.includes("pad")) {
    laborHours = 14;
    materialsCost += 1300;
    equipmentCost += 500;
    scope =
      "Prepare pad area, grade, compact, and place material suitable for slab or structure support.";
    recommendations.push("Check subgrade condition and drainage before final pricing.");
  }

  if (text.includes("fence")) {
    laborHours = 16;
    laborRate = 90;
    materialsCost = 1400;
    equipmentCost = 180;
    scope =
      "Remove or install fence components, set posts, align runs, and complete standard fence work.";
    recommendations.push("Verify footage, gate count, and post spacing.");
  }

  if (text.includes("brush") || text.includes("clear")) {
    laborHours = 14;
    materialsCost = 180;
    equipmentCost = 750;
    scope =
      "Clear brush, vegetation, and light debris from the requested work area.";
    recommendations.push("Confirm dump/disposal expectations and access conditions.");
  }

  if (text.includes("concrete")) {
    laborHours = 18;
    materialsCost += 2200;
    equipmentCost += 650;
    scope =
      "Perform concrete-related removal, prep, placement, or finishing based on the described work.";
    recommendations.push("Verify thickness, reinforcement, and finish type.");
  }

  if (text.includes("demo") || text.includes("demolition") || text.includes("remove")) {
    laborHours += 8;
    equipmentCost += 450;
    materialsCost += 150;
    scope =
      "Remove existing material or structure, load debris, and leave site broom-clean unless otherwise stated.";
    recommendations.push("Confirm disposal fees and haul-off distance.");
  }

  if (text.includes("excavat") || text.includes("dig") || text.includes("trench")) {
    laborHours += 10;
    equipmentCost += 800;
    materialsCost += 100;
    scope =
      "Excavate, shape, and clean the work area to the described dimensions and purpose.";
    recommendations.push("Call utility locate before digging.");
  }

  if (text.includes("alternator") || text.includes("repair") || text.includes("mechanic")) {
    laborHours = 4;
    laborRate = 110;
    materialsCost = 380;
    equipmentCost = 60;
    scope =
      "Diagnose, remove, replace, test, and verify proper operation for the described repair.";
    recommendations.push("Confirm exact part number before ordering.");
  }

  laborHours = Math.round(laborHours * sizeMultiplier);
  materialsCost = Math.round(materialsCost * sizeMultiplier);
  equipmentCost = Math.round(equipmentCost * Math.min(sizeMultiplier, 1.8));

  const laborCost = laborHours * laborRate;
  const subtotal = laborCost + materialsCost + equipmentCost;
  const markupAmount = Math.round(subtotal * (markupPercent / 100));
  const total = subtotal + markupAmount;

  if (recommendations.length === 0) {
    recommendations.push("Verify final measurements on site.");
    recommendations.push("Confirm material pricing before sending.");
  }

  return {
    jobType,
    laborHours,
    laborRate,
    laborCost,
    materialsCost,
    equipmentCost,
    subtotal,
    markupPercent,
    markupAmount,
    total,
    scope,
    recommendations,
  };
}

function formatEstimate(
  data: EstimateData,
  customerName: string,
  description: string,
  language: Language
): string {
  const t = languageLabels[language];

  return `${t.estimateTitle}

${t.estimateFor}: ${customerName || "Walk-in / Unassigned"}

${t.customer}: ${customerName || "Not specified"}
${t.jobDescription}: ${description}
${t.detectedJobType}: ${data.jobType}

${t.scopeOfWork}:
${data.scope}

${t.laborHours}: ${data.laborHours}
${t.laborRate}: ${money(data.laborRate)}
${t.laborCost}: ${money(data.laborCost)}
${t.materialsCost}: ${money(data.materialsCost)}
${t.equipmentCost}: ${money(data.equipmentCost)}
${t.subtotal}: ${money(data.subtotal)}
${t.markup}: ${data.markupPercent}% (${money(data.markupAmount)})

${t.totalEstimate}: ${money(data.total)}

${t.recommendations}:
- ${data.recommendations.join("\n- ")}

${t.generatedBy}
${t.currencyNote}`;
}

function translateText(text: string, language: Language): string {
  if (language === "English") return text;

  const replacements: Record<Language, Array<[string, string]>> = {
    English: [],
    Spanish: [
      ["PROFESSIONAL ESTIMATE", "PRESUPUESTO PROFESIONAL"],
      ["Estimate For", "Presupuesto Para"],
      ["Customer", "Cliente"],
      ["Job Description", "Descripción del Trabajo"],
      ["Detected Job Type", "Tipo de Trabajo Detectado"],
      ["Scope of Work", "Alcance del Trabajo"],
      ["Estimated Labor Hours", "Horas de Mano de Obra Estimadas"],
      ["Labor Rate", "Tarifa de Mano de Obra"],
      ["Labor Cost", "Costo de Mano de Obra"],
      ["Materials Cost", "Costo de Materiales"],
      ["Equipment Cost", "Costo de Equipo"],
      ["Subtotal", "Subtotal"],
      ["Markup", "Margen"],
      ["Total Estimate", "Presupuesto Total"],
      ["Recommendations", "Recomendaciones"],
      ["Generated by Tradesman AI", "Generado por Tradesman AI"],
      ["Not specified", "No especificado"],
      ["Walk-in / Unassigned", "Cliente sin asignar"],
    ],
    French: [
      ["PROFESSIONAL ESTIMATE", "DEVIS PROFESSIONNEL"],
      ["Estimate For", "Devis Pour"],
      ["Customer", "Client"],
      ["Job Description", "Description du Travail"],
      ["Detected Job Type", "Type de Travail Détecté"],
      ["Scope of Work", "Étendue des Travaux"],
      ["Estimated Labor Hours", "Heures de Main-d'œuvre Estimées"],
      ["Labor Rate", "Taux de Main-d'œuvre"],
      ["Labor Cost", "Coût de Main-d'œuvre"],
      ["Materials Cost", "Coût des Matériaux"],
      ["Equipment Cost", "Coût de l'Équipement"],
      ["Subtotal", "Sous-total"],
      ["Markup", "Marge"],
      ["Total Estimate", "Devis Total"],
      ["Recommendations", "Recommandations"],
      ["Generated by Tradesman AI", "Généré par Tradesman AI"],
      ["Not specified", "Non spécifié"],
      ["Walk-in / Unassigned", "Client non attribué"],
    ],
    German: [
      ["PROFESSIONAL ESTIMATE", "PROFESSIONELLES ANGEBOT"],
      ["Estimate For", "Angebot Für"],
      ["Customer", "Kunde"],
      ["Job Description", "Arbeitsbeschreibung"],
      ["Detected Job Type", "Erkannter Arbeitstyp"],
      ["Scope of Work", "Leistungsumfang"],
      ["Estimated Labor Hours", "Geschätzte Arbeitsstunden"],
      ["Labor Rate", "Stundensatz"],
      ["Labor Cost", "Arbeitskosten"],
      ["Materials Cost", "Materialkosten"],
      ["Equipment Cost", "Gerätekosten"],
      ["Subtotal", "Zwischensumme"],
      ["Markup", "Aufschlag"],
      ["Total Estimate", "Gesamtangebot"],
      ["Recommendations", "Empfehlungen"],
      ["Generated by Tradesman AI", "Erstellt von Tradesman AI"],
      ["Not specified", "Nicht angegeben"],
      ["Walk-in / Unassigned", "Nicht zugeordnet"],
    ],
    Portuguese: [
      ["PROFESSIONAL ESTIMATE", "ORÇAMENTO PROFISSIONAL"],
      ["Estimate For", "Orçamento Para"],
      ["Customer", "Cliente"],
      ["Job Description", "Descrição do Serviço"],
      ["Detected Job Type", "Tipo de Serviço Detectado"],
      ["Scope of Work", "Escopo do Trabalho"],
      ["Estimated Labor Hours", "Horas de Mão de Obra Estimadas"],
      ["Labor Rate", "Taxa de Mão de Obra"],
      ["Labor Cost", "Custo de Mão de Obra"],
      ["Materials Cost", "Custo de Materiais"],
      ["Equipment Cost", "Custo de Equipamento"],
      ["Subtotal", "Subtotal"],
      ["Markup", "Margem"],
      ["Total Estimate", "Orçamento Total"],
      ["Recommendations", "Recomendações"],
      ["Generated by Tradesman AI", "Gerado por Tradesman AI"],
      ["Not specified", "Não especificado"],
      ["Walk-in / Unassigned", "Cliente não atribuído"],
    ],
  };

  let result = text;
  for (const [from, to] of replacements[language]) {
    result = result.split(from).join(to);
  }
  return result;
}

function quoteRangeFromLead(description: string, score: number): string {
  const estimate = generateEstimateData(description || "General contractor job");

  let low = Math.round(estimate.total * 0.85);
  let high = Math.round(estimate.total * 1.2);

  if (detectJobType(description) === "Mechanical Repair") {
    low = Math.round(estimate.total * 0.9);
    high = Math.round(estimate.total * 1.1);
  }

  if (score >= 70) {
    low = Math.round(low * 1.05);
    high = Math.round(high * 1.1);
  }

  return `${money(low)} - ${money(high)}`;
}

function suggestedReply(lead: LeadRow): string {
  const jobType = detectJobType(lead.description || lead.title || "");
  const range = quoteRangeFromLead(
    `${lead.title}\n${lead.description}`,
    Number(lead.score || 0)
  );

  return `Hi ${lead.contact_name || "there"} — thanks for reaching out about your ${jobType.toLowerCase()} project in ${lead.city || "your area"}. Based on what you sent, this looks like a rough range of ${range}. If you'd like, I can take a closer look and get you a firm quote.`;
}

function buttonStyle(
  variant: "primary" | "secondary" = "primary"
): React.CSSProperties {
  return {
    padding: "12px 16px",
    borderRadius: 10,
    border: variant === "primary" ? "none" : "1px solid #d1d5db",
    background: variant === "primary" ? "#7c3aed" : "white",
    color: variant === "primary" ? "white" : "#111827",
    fontWeight: 700,
    cursor: "pointer",
  };
}

function inputBox(): React.CSSProperties {
  return {
    width: "100%",
    padding: 12,
    borderRadius: 10,
    border: "1px solid #d1d5db",
    boxSizing: "border-box",
  };
}

function PricingCard({
  title,
  price,
  bullets,
  buttonText,
  onClick,
  highlighted,
}: {
  title: string;
  price: string;
  bullets: string[];
  buttonText: string;
  onClick: () => void;
  highlighted: boolean;
}) {
  return (
    <div
      style={{
        border: highlighted ? "2px solid #7c3aed" : "1px solid #e5e7eb",
        borderRadius: 12,
        padding: 16,
        background: highlighted ? "#faf5ff" : "white",
      }}
    >
      <div style={{ fontWeight: 800, fontSize: 18 }}>{title}</div>
      <div style={{ fontWeight: 900, fontSize: 28, margin: "8px 0 12px" }}>
        {price}
      </div>
      <ul style={{ paddingLeft: 18, marginTop: 0, color: "#374151" }}>
        {bullets.map((b) => (
          <li key={b} style={{ marginBottom: 6 }}>
            {b}
          </li>
        ))}
      </ul>
      <button
        onClick={onClick}
        style={buttonStyle(highlighted ? "primary" : "secondary")}
      >
        {buttonText}
      </button>
    </div>
  );
}

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <div
      style={{
        border: "1px solid #e5e7eb",
        borderRadius: 12,
        padding: 14,
        background: "#f8fafc",
      }}
    >
      <div style={{ color: "#6b7280", fontSize: 12 }}>{label}</div>
      <div style={{ fontWeight: 900, fontSize: 24 }}>{value}</div>
    </div>
  );
}

function LeadCard({
  lead,
  onStatus,
  onDelete,
  onLoadReply,
}: {
  lead: LeadRow;
  onStatus: (id: string, status: string) => void;
  onDelete: (id: string) => void;
  onLoadReply: (text: string) => void;
}) {
  const combined = `${lead.title}\n${lead.description}\n${lead.city}\n${lead.budget}\n${lead.contact_name}\n${lead.contact_info}`;
  const scored = scoreLead(combined);
  const bucket = scoreBucket(Number(lead.score || 0));
  const reply = suggestedReply(lead);
  const range = quoteRangeFromLead(
    `${lead.title}\n${lead.description}`,
    Number(lead.score || 0)
  );

  return (
    <div
      style={{
        border: "1px solid #e5e7eb",
        borderRadius: 12,
        padding: 14,
        background: "white",
      }}
    >
      <div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}>
        <div>
          <div style={{ fontWeight: 800 }}>{lead.title || "Untitled Lead"}</div>
          <div style={{ color: "#6b7280", fontSize: 13 }}>
            {lead.city || "No city"} • {lead.source || "manual"} • {lead.created_at}
          </div>
        </div>
        <div
          style={{
            padding: "6px 10px",
            borderRadius: 999,
            background:
              bucket === "Hot"
                ? "#fee2e2"
                : bucket === "Warm"
                ? "#fef3c7"
                : "#e5e7eb",
            fontWeight: 800,
            whiteSpace: "nowrap",
          }}
        >
          {bucket} • {lead.score}
        </div>
      </div>

      <div style={{ marginTop: 10, whiteSpace: "pre-wrap" }}>
        {lead.description || "No description"}
      </div>

      <div style={{ marginTop: 10, color: "#374151", lineHeight: 1.7 }}>
        <div>Contact: {lead.contact_name || "-"} / {lead.contact_info || "-"}</div>
        <div>Budget: {lead.budget || "-"}</div>
        <div>Status: <strong>{lead.status}</strong></div>
        <div>
          Detected Job:{" "}
          <strong>{detectJobType(`${lead.title} ${lead.description}`)}</strong>
        </div>
        <div>Suggested Quote Range: <strong>{range}</strong></div>
      </div>

      <div
        style={{
          marginTop: 10,
          padding: 12,
          borderRadius: 10,
          background: "#f8fafc",
          border: "1px solid #e5e7eb",
        }}
      >
        <div style={{ fontWeight: 700, marginBottom: 6 }}>Score Reasons</div>
        <div style={{ fontSize: 14, color: "#374151" }}>
          {scored.reasons.length
            ? scored.reasons.join(" • ")
            : "No strong signals found"}
        </div>
      </div>

      <div
        style={{
          marginTop: 10,
          padding: 12,
          borderRadius: 10,
          background: "#f8fafc",
          border: "1px solid #e5e7eb",
        }}
      >
        <div style={{ fontWeight: 700, marginBottom: 6 }}>Suggested Reply</div>
        <div style={{ whiteSpace: "pre-wrap", fontSize: 14 }}>{reply}</div>
        <div style={{ marginTop: 10 }}>
          <button onClick={() => onLoadReply(reply)} style={buttonStyle("secondary")}>
            Load Reply Into Output
          </button>
        </div>
      </div>

      <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 12 }}>
        <button
          onClick={() => onStatus(lead.id, "contacted")}
          style={buttonStyle("secondary")}
        >
          Mark Contacted
        </button>
        <button
          onClick={() => onStatus(lead.id, "quoted")}
          style={buttonStyle("secondary")}
        >
          Mark Quoted
        </button>
        <button
          onClick={() => onStatus(lead.id, "won")}
          style={buttonStyle("secondary")}
        >
          Mark Won
        </button>
        <button
          onClick={() => onDelete(lead.id)}
          style={buttonStyle("secondary")}
        >
          Delete
        </button>
      </div>
    </div>
  );
}

function PipelineColumn({
  title,
  bg,
  leads,
  onStatus,
  onDelete,
  onLoadReply,
}: {
  title: string;
  bg: string;
  leads: LeadRow[];
  onStatus: (id: string, status: string) => void;
  onDelete: (id: string) => void;
  onLoadReply: (text: string) => void;
}) {
  return (
    <div
      style={{
        background: bg,
        border: "1px solid #e5e7eb",
        borderRadius: 14,
        padding: 12,
        minHeight: 300,
      }}
    >
      <div style={{ fontWeight: 900, marginBottom: 12 }}>{title}</div>
      <div style={{ display: "grid", gap: 12 }}>
        {leads.length === 0 ? (
          <div style={{ color: "#6b7280" }}>No leads in this bucket.</div>
        ) : (
          leads.map((lead) => (
            <LeadCard
              key={lead.id}
              lead={lead}
              onStatus={onStatus}
              onDelete={onDelete}
              onLoadReply={onLoadReply}
            />
          ))
        )}
      </div>
    </div>
  );
}

function LandingStat({ title, text }: { title: string; text: string }) {
  return (
    <div
      style={{
        background: "#111827",
        border: "1px solid #334155",
        borderRadius: 16,
        padding: 16,
      }}
    >
      <div style={{ fontWeight: 900, marginBottom: 8 }}>{title}</div>
      <div style={{ color: "#a8b3c7", lineHeight: 1.6 }}>{text}</div>
    </div>
  );
}

export default function App() {
  const [session, setSession] = useState<any>(null);
  const [authLoading, setAuthLoading] = useState(true);
  const [authMode, setAuthMode] = useState<"signin" | "signup">("signin");
  const [authEmail, setAuthEmail] = useState("");
  const [authPassword, setAuthPassword] = useState("");
  const [authMessage, setAuthMessage] = useState("");

  const [customers, setCustomers] = useState<Customer[]>([]);
  const [customerName, setCustomerName] = useState("");
  const [selectedCustomer, setSelectedCustomer] = useState("");

  const [jobDescription, setJobDescription] = useState("");
  const [language, setLanguage] = useState<Language>("English");
  const [translateLanguage, setTranslateLanguage] = useState<Language>("Spanish");
  const [output, setOutput] = useState("");
  const [translationPreview, setTranslationPreview] = useState("");
  const [selectedText, setSelectedText] = useState("");

  const [leadTitle, setLeadTitle] = useState("");
  const [leadDescription, setLeadDescription] = useState("");
  const [leadCity, setLeadCity] = useState("");
  const [leadContactName, setLeadContactName] = useState("");
  const [leadContactInfo, setLeadContactInfo] = useState("");
  const [leadBudget, setLeadBudget] = useState("");
  const [leads, setLeads] = useState<LeadRow[]>([]);
  const [leadStatusFilter, setLeadStatusFilter] = useState("all");
  const [leadBucketFilter, setLeadBucketFilter] = useState("all");

  const outputRef = useRef<HTMLTextAreaElement | null>(null);

  useEffect(() => {
    let mounted = true;

    supabase.auth.getSession().then((result: any) => {
      if (!mounted) return;
      setSession(result?.data?.session ?? null);
      setAuthLoading(false);
    });

    const authListener = supabase.auth.onAuthStateChange(
      async (_event: any, nextSession: any) => {
        setSession(nextSession);
        setAuthLoading(false);
      }
    );

    return () => {
      mounted = false;
      authListener?.data?.subscription?.unsubscribe?.();
    };
  }, []);

  useEffect(() => {
    if (session?.user?.id) {
      void loadLeads(session.user.id);
    } else {
      setLeads([]);
    }
  }, [session]);

  async function loadLeads(userId: string) {
    const result = await supabase
      .from("leads")
      .select("*")
      .eq("user_id", userId)
      .order("score", { ascending: false })
      .order("created_at", { ascending: false });

    if (!result.error) {
      const mapped = (result.data || []).map((row: any) => ({
        ...row,
        created_at: row.created_at
          ? new Date(row.created_at).toLocaleString()
          : "",
      }));
      setLeads(mapped);
    }
  }

  async function handleSignUp() {
    setAuthMessage("");
    if (!authEmail || !authPassword) {
      setAuthMessage("Enter email and password.");
      return;
    }

    const result = await supabase.auth.signUp({
      email: authEmail,
      password: authPassword,
      options: {
        emailRedirectTo: "https://tradesman-ai-pro.vercel.app",
      },
    });

    if (result.error) {
      setAuthMessage(result.error.message);
      return;
    }

    setAuthMessage("Account created. Check your email if confirmation is required.");
  }

  async function handleSignIn() {
    setAuthMessage("");
    if (!authEmail || !authPassword) {
      setAuthMessage("Enter email and password.");
      return;
    }

    const result = await supabase.auth.signInWithPassword({
      email: authEmail,
      password: authPassword,
    });

    if (result.error) {
      setAuthMessage(result.error.message);
      return;
    }

    setAuthMessage("Signed in.");
  }

  async function handleSignOut() {
    await supabase.auth.signOut();
    setAuthMessage("");
  }

  async function addLead() {
    if (!session?.user?.id) {
      alert("Sign in first.");
      return;
    }

    const combined = `${leadTitle}\n${leadDescription}\n${leadCity}\n${leadBudget}\n${leadContactName}\n${leadContactInfo}`;
    const scored = scoreLead(combined);

    const result = await supabase.from("leads").insert({
      user_id: session.user.id,
      source: "manual",
      title: leadTitle,
      description: leadDescription,
      city: leadCity,
      contact_name: leadContactName,
      contact_info: leadContactInfo,
      budget: leadBudget,
      score: scored.score,
      status: "new",
    });

    if (result.error) {
      alert(result.error.message);
      return;
    }

    setLeadTitle("");
    setLeadDescription("");
    setLeadCity("");
    setLeadContactName("");
    setLeadContactInfo("");
    setLeadBudget("");

    await loadLeads(session.user.id);
  }

  async function updateLeadStatus(id: string, status: string) {
    if (!session?.user?.id) return;

    const result = await supabase.from("leads").update({ status }).eq("id", id);
    if (result.error) {
      alert(result.error.message);
      return;
    }

    await loadLeads(session.user.id);
  }

  async function deleteLead(id: string) {
    if (!session?.user?.id) return;

    const result = await supabase.from("leads").delete().eq("id", id);
    if (result.error) {
      alert(result.error.message);
      return;
    }

    await loadLeads(session.user.id);
  }

  const liveEstimate = useMemo(() => {
    return generateEstimateData(jobDescription || "General contractor job");
  }, [jobDescription]);

  const scoredDraftLead = useMemo(() => {
    const combined = `${leadTitle}\n${leadDescription}\n${leadCity}\n${leadBudget}\n${leadContactName}\n${leadContactInfo}`;
    return scoreLead(combined);
  }, [
    leadTitle,
    leadDescription,
    leadCity,
    leadBudget,
    leadContactName,
    leadContactInfo,
  ]);

  const filteredLeads = useMemo(() => {
    return leads.filter((lead) => {
      const statusPass =
        leadStatusFilter === "all" ? true : lead.status === leadStatusFilter;
      const bucketPass =
        leadBucketFilter === "all"
          ? true
          : scoreBucket(Number(lead.score || 0)) === leadBucketFilter;
      return statusPass && bucketPass;
    });
  }, [leads, leadStatusFilter, leadBucketFilter]);

  const hotLeads = useMemo(
    () => filteredLeads.filter((lead) => scoreBucket(Number(lead.score || 0)) === "Hot"),
    [filteredLeads]
  );
  const warmLeads = useMemo(
    () => filteredLeads.filter((lead) => scoreBucket(Number(lead.score || 0)) === "Warm"),
    [filteredLeads]
  );
  const coldLeads = useMemo(
    () => filteredLeads.filter((lead) => scoreBucket(Number(lead.score || 0)) === "Cold"),
    [filteredLeads]
  );

  const leadStats = useMemo(() => {
    return {
      total: leads.length,
      hot: leads.filter((l) => scoreBucket(Number(l.score || 0)) === "Hot").length,
      warm: leads.filter((l) => scoreBucket(Number(l.score || 0)) === "Warm").length,
      cold: leads.filter((l) => scoreBucket(Number(l.score || 0)) === "Cold").length,
      won: leads.filter((l) => l.status === "won").length,
      quoted: leads.filter((l) => l.status === "quoted").length,
    };
  }, [leads]);

  const addCustomer = () => {
    if (!customerName.trim()) return;
    setCustomers([
      ...customers,
      {
        name: customerName.trim(),
        created: new Date().toLocaleDateString(),
      },
    ]);
    setCustomerName("");
  };

  const generateEstimate = () => {
    const estimate = generateEstimateData(jobDescription || "General contractor job");
    const text = formatEstimate(
      estimate,
      selectedCustomer,
      jobDescription || "General contractor job",
      language
    );
    setOutput(text);
    setTranslationPreview("");
  };

  const copyOutput = async () => {
    await navigator.clipboard.writeText(output);
  };

  const translateFullOutput = () => {
    if (!output.trim()) return;
    const translated = translateText(output, translateLanguage);
    setOutput(translated);
    setTranslationPreview(translated);
  };

  const handleSelection = () => {
    const textarea = outputRef.current;
    if (!textarea) return;

    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const text = textarea.value.substring(start, end);
    setSelectedText(text);
  };

  const translateSelectedText = () => {
    const textarea = outputRef.current;
    if (!textarea) return;
    if (!selectedText.trim()) return;

    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const translatedSelection = translateText(selectedText, translateLanguage);

    const newOutput =
      output.substring(0, start) + translatedSelection + output.substring(end);

    setOutput(newOutput);
    setTranslationPreview(translatedSelection);
  };

  const replaceAllWithTranslatedPreview = () => {
    if (!translationPreview.trim()) return;
    setOutput(translationPreview);
  };

  if (authLoading) {
    return <div style={{ padding: 32 }}>Loading...</div>;
  }

  if (!session) {
    return (
      <div
        style={{
          minHeight: "100vh",
          background: "#0f1724",
          color: "#edf2f7",
          fontFamily: "Arial, sans-serif",
          padding: 24,
        }}
      >
        <div style={{ maxWidth: 1100, margin: "0 auto" }}>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1.2fr 0.8fr",
              gap: 24,
              alignItems: "stretch",
            }}
          >
            <div
              style={{
                background: "linear-gradient(180deg, #17202d, #111827)",
                border: "1px solid #334155",
                borderRadius: 22,
                padding: 28,
              }}
            >
              <div
                style={{
                  display: "inline-block",
                  padding: "8px 12px",
                  borderRadius: 999,
                  background: "#241f3c",
                  color: "#c4b5fd",
                  fontWeight: 800,
                  marginBottom: 18,
                }}
              >
                AI Business Software for Contractors
              </div>

              <div
                style={{
                  fontSize: 48,
                  fontWeight: 900,
                  lineHeight: 1.05,
                  marginBottom: 16,
                }}
              >
                Quote jobs faster, score leads, and reply with AI.
              </div>

              <div
                style={{
                  color: "#a8b3c7",
                  fontSize: 18,
                  lineHeight: 1.6,
                  marginBottom: 24,
                }}
              >
                Tradesman AI helps contractors manage leads, build estimates,
                translate messages, and respond faster.
              </div>

              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
                  gap: 14,
                }}
              >
                <LandingStat
                  title="Lead Inbox"
                  text="Paste incoming jobs, auto-score them, and track pipeline status."
                />
                <LandingStat
                  title="Estimate Engine"
                  text="Generate quote ranges and professional estimate text fast."
                />
                <LandingStat
                  title="Translation Tools"
                  text="Translate full output or selected text for real field use."
                />
              </div>
            </div>

            <div
              style={{
                background: "#17202d",
                border: "1px solid #334155",
                borderRadius: 22,
                padding: 24,
              }}
            >
              <div style={{ fontSize: 34, fontWeight: 900, marginBottom: 8 }}>
                Tradesman AI
              </div>
              <div style={{ color: "#a8b3c7", marginBottom: 16 }}>
                Sign in or create your account.
              </div>

              <div style={{ display: "flex", gap: 10, marginBottom: 16 }}>
                <button
                  onClick={() => setAuthMode("signin")}
                  style={{
                    flex: 1,
                    padding: "12px 14px",
                    borderRadius: 12,
                    border: "1px solid #334155",
                    background: authMode === "signin" ? "#9b87f5" : "#1d2939",
                    color: "white",
                    fontWeight: 800,
                    cursor: "pointer",
                  }}
                >
                  Sign In
                </button>
                <button
                  onClick={() => setAuthMode("signup")}
                  style={{
                    flex: 1,
                    padding: "12px 14px",
                    borderRadius: 12,
                    border: "1px solid #334155",
                    background: authMode === "signup" ? "#9b87f5" : "#1d2939",
                    color: "white",
                    fontWeight: 800,
                    cursor: "pointer",
                  }}
                >
                  Sign Up
                </button>
              </div>

              <div style={{ display: "grid", gap: 12 }}>
                <input
                  type="email"
                  placeholder="Email"
                  value={authEmail}
                  onChange={(e) => setAuthEmail(e.target.value)}
                  style={{
                    width: "100%",
                    boxSizing: "border-box",
                    background: "#0f1724",
                    color: "#edf2f7",
                    border: "1px solid #334155",
                    borderRadius: 10,
                    padding: "12px 12px",
                    outline: "none",
                  }}
                />
                <input
                  type="password"
                  placeholder="Password"
                  value={authPassword}
                  onChange={(e) => setAuthPassword(e.target.value)}
                  style={{
                    width: "100%",
                    boxSizing: "border-box",
                    background: "#0f1724",
                    color: "#edf2f7",
                    border: "1px solid #334155",
                    borderRadius: 10,
                    padding: "12px 12px",
                    outline: "none",
                  }}
                />
              </div>

              <div style={{ display: "flex", gap: 10, marginTop: 18 }}>
                {authMode === "signin" ? (
                  <button
                    onClick={handleSignIn}
                    style={{
                      background: "#9b87f5",
                      color: "white",
                      border: "none",
                      borderRadius: 12,
                      padding: "13px 18px",
                      fontWeight: 800,
                      cursor: "pointer",
                      width: "100%",
                    }}
                  >
                    Sign In
                  </button>
                ) : (
                  <button
                    onClick={handleSignUp}
                    style={{
                      background: "#9b87f5",
                      color: "white",
                      border: "none",
                      borderRadius: 12,
                      padding: "13px 18px",
                      fontWeight: 800,
                      cursor: "pointer",
                      width: "100%",
                    }}
                  >
                    Create Account
                  </button>
                )}
              </div>

              <div style={{ color: "#a8b3c7", marginTop: 14, minHeight: 24 }}>
                {authMessage}
              </div>

              <div
                style={{
                  marginTop: 22,
                  padding: 16,
                  border: "1px solid #334155",
                  borderRadius: 14,
                  background: "#111827",
                }}
              >
                <div style={{ fontWeight: 800, marginBottom: 10 }}>Pricing</div>
                <div style={{ color: "#a8b3c7", lineHeight: 1.7 }}>
                  <strong>Basic — $19/mo</strong>
                  <br />
                  CRM, estimates, translations
                  <br />
                  <br />
                  <strong>Pro — $49/mo</strong>
                  <br />
                  Lead inbox, AI replies, quote ranges
                  <br />
                  <br />
                  <strong>Team — $99/mo</strong>
                  <br />
                  Team workflow foundation
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      style={{
        fontFamily: "Arial, sans-serif",
        maxWidth: "1180px",
        margin: "auto",
        padding: "32px",
        color: "#111827",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          gap: 12,
          alignItems: "center",
          flexWrap: "wrap",
          marginBottom: 20,
        }}
      >
        <div>
          <h1 style={{ marginBottom: 8 }}>Tradesman AI</h1>
          <p style={{ color: "#4b5563", marginTop: 0 }}>
            Signed in as {session.user?.email || "user"}
          </p>
        </div>
        <button onClick={handleSignOut} style={buttonStyle("secondary")}>
          Sign Out
        </button>
      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: 24,
          marginTop: 8,
          marginBottom: 36,
        }}
      >
        <div
          style={{
            border: "1px solid #e5e7eb",
            borderRadius: 14,
            padding: 20,
          }}
        >
          <h2 style={{ marginTop: 0 }}>Customer Manager</h2>

          <div style={{ display: "flex", gap: 10, marginBottom: 14 }}>
            <input
              value={customerName}
              onChange={(e) => setCustomerName(e.target.value)}
              placeholder="Customer Name"
              style={{
                flex: 1,
                padding: "12px",
                borderRadius: 10,
                border: "1px solid #d1d5db",
              }}
            />
            <button onClick={addCustomer} style={buttonStyle()}>
              Add
            </button>
          </div>

          <select
            value={selectedCustomer}
            onChange={(e) => setSelectedCustomer(e.target.value)}
            style={{
              width: "100%",
              padding: "12px",
              borderRadius: 10,
              border: "1px solid #d1d5db",
              marginBottom: 16,
            }}
          >
            <option value="">Select Customer</option>
            {customers.map((c, i) => (
              <option key={`${c.name}-${i}`} value={c.name}>
                {c.name}
              </option>
            ))}
          </select>

          <div style={{ maxHeight: 220, overflowY: "auto" }}>
            {customers.length === 0 ? (
              <div style={{ color: "#6b7280" }}>No customers yet.</div>
            ) : (
              customers.map((c, i) => (
                <div
                  key={`${c.name}-${i}`}
                  style={{
                    padding: "10px 0",
                    borderBottom: "1px solid #f1f5f9",
                  }}
                >
                  <strong>{c.name}</strong>
                  <div style={{ fontSize: 12, color: "#6b7280" }}>
                    Added {c.created}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        <div
          style={{
            border: "1px solid #e5e7eb",
            borderRadius: 14,
            padding: 20,
          }}
        >
          <h2 style={{ marginTop: 0 }}>Pricing</h2>

          <div style={{ display: "grid", gap: 12 }}>
            <PricingCard
              title="Basic"
              price="$19/mo"
              bullets={[
                "Customer manager",
                "Job notes",
                "Estimate output",
                "Translation tools",
              ]}
              buttonText="Subscribe"
              onClick={() => window.open(BASIC_STRIPE_LINK, "_blank")}
              highlighted={false}
            />
            <PricingCard
              title="Pro"
              price="$49/mo"
              bullets={[
                "Everything in Basic",
                "Lead inbox",
                "AI lead reply",
                "Quote range engine",
              ]}
              buttonText="Upgrade"
              onClick={() => window.open(PRO_STRIPE_LINK, "_blank")}
              highlighted={true}
            />
            <PricingCard
              title="Team"
              price="$99/mo"
              bullets={[
                "Everything in Pro",
                "Shared lead workflow later",
                "Team dashboard later",
                "Priority support",
              ]}
              buttonText="Coming Soon"
              onClick={() => alert("Team plan coming soon")}
              highlighted={false}
            />
          </div>
        </div>
      </div>

      <div
        style={{
          border: "1px solid #e5e7eb",
          borderRadius: 14,
          padding: 20,
          marginBottom: 24,
        }}
      >
        <h2 style={{ marginTop: 0 }}>AI Estimate Engine</h2>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1.2fr 0.4fr 0.4fr",
            gap: 12,
            marginBottom: 14,
          }}
        >
          <textarea
            value={jobDescription}
            onChange={(e) => setJobDescription(e.target.value)}
            placeholder="Type the job in plain English. Example: Install 80ft privacy fence with one gate and remove old fence."
            style={{
              minHeight: 110,
              padding: 12,
              borderRadius: 10,
              border: "1px solid #d1d5db",
              resize: "vertical",
            }}
          />

          <select
            value={language}
            onChange={(e) => setLanguage(e.target.value as Language)}
            style={{
              padding: "12px",
              borderRadius: 10,
              border: "1px solid #d1d5db",
              height: 46,
            }}
          >
            {LANGUAGES.map((lang) => (
              <option key={lang} value={lang}>
                {lang}
              </option>
            ))}
          </select>

          <button onClick={generateEstimate} style={buttonStyle()}>
            Generate Estimate
          </button>
        </div>

        <div
          style={{
            background: "#f8fafc",
            border: "1px solid #e5e7eb",
            borderRadius: 12,
            padding: 16,
            marginBottom: 18,
          }}
        >
          <strong>Live Estimate Snapshot</strong>
          <div style={{ marginTop: 10, lineHeight: 1.8 }}>
            <div>Job Type: {liveEstimate.jobType}</div>
            <div>Labor Hours: {liveEstimate.laborHours}</div>
            <div>Labor Cost: {money(liveEstimate.laborCost)}</div>
            <div>Materials Cost: {money(liveEstimate.materialsCost)}</div>
            <div>Equipment Cost: {money(liveEstimate.equipmentCost)}</div>
            <div>Markup: {liveEstimate.markupPercent}%</div>
            <div>
              <strong>Total: {money(liveEstimate.total)}</strong>
            </div>
          </div>
        </div>
      </div>

      <div
        style={{
          border: "1px solid #e5e7eb",
          borderRadius: 14,
          padding: 20,
          marginBottom: 24,
        }}
      >
        <h2 style={{ marginTop: 0 }}>Language + Translate Tools</h2>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "0.4fr 1fr",
            gap: 12,
            alignItems: "center",
            marginBottom: 12,
          }}
        >
          <select
            value={translateLanguage}
            onChange={(e) => setTranslateLanguage(e.target.value as Language)}
            style={{
              padding: "12px",
              borderRadius: 10,
              border: "1px solid #d1d5db",
            }}
          >
            {LANGUAGES.map((lang) => (
              <option key={lang} value={lang}>
                Translate to {lang}
              </option>
            ))}
          </select>

          <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
            <button onClick={translateFullOutput} style={buttonStyle()}>
              Translate Full Output
            </button>
            <button onClick={translateSelectedText} style={buttonStyle()}>
              Translate Selected Text
            </button>
            <button onClick={copyOutput} style={buttonStyle("secondary")}>
              Copy Output
            </button>
          </div>
        </div>

        <div style={{ color: "#6b7280", fontSize: 13, marginBottom: 12 }}>
          Highlight text inside the output box, then click{" "}
          <strong>Translate Selected Text</strong>.
        </div>

        <textarea
          ref={outputRef}
          value={output}
          onChange={(e) => setOutput(e.target.value)}
          onSelect={handleSelection}
          placeholder="Generated estimate output or AI reply will appear here..."
          style={{
            width: "100%",
            minHeight: 320,
            padding: 14,
            borderRadius: 12,
            border: "1px solid #d1d5db",
            resize: "vertical",
            boxSizing: "border-box",
            marginBottom: 14,
          }}
        />

        <div
          style={{
            background: "#f8fafc",
            border: "1px solid #e5e7eb",
            borderRadius: 12,
            padding: 14,
          }}
        >
          <div style={{ fontWeight: 700, marginBottom: 8 }}>
            Translation Preview
          </div>
          <div
            style={{
              minHeight: 80,
              whiteSpace: "pre-wrap",
              color: translationPreview ? "#111827" : "#6b7280",
              marginBottom: 12,
            }}
          >
            {translationPreview || "Translated text preview will appear here."}
          </div>

          <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
            <button
              onClick={replaceAllWithTranslatedPreview}
              style={buttonStyle()}
            >
              Replace Output With Preview
            </button>
            <button
              onClick={() => navigator.clipboard.writeText(translationPreview)}
              style={buttonStyle("secondary")}
            >
              Copy Preview
            </button>
          </div>
        </div>
      </div>

      <div
        style={{
          border: "1px solid #e5e7eb",
          borderRadius: 14,
          padding: 20,
          marginBottom: 24,
        }}
      >
        <h2 style={{ marginTop: 0 }}>Lead Inbox</h2>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(4, 1fr)",
            gap: 12,
            marginBottom: 16,
          }}
        >
          <StatCard label="Total Leads" value={String(leadStats.total)} />
          <StatCard label="Hot Leads" value={String(leadStats.hot)} />
          <StatCard label="Quoted" value={String(leadStats.quoted)} />
          <StatCard label="Won" value={String(leadStats.won)} />
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: 12,
            marginBottom: 12,
          }}
        >
          <input
            value={leadTitle}
            onChange={(e) => setLeadTitle(e.target.value)}
            placeholder="Lead title"
            style={inputBox()}
          />
          <input
            value={leadCity}
            onChange={(e) => setLeadCity(e.target.value)}
            placeholder="City"
            style={inputBox()}
          />
        </div>

        <textarea
          value={leadDescription}
          onChange={(e) => setLeadDescription(e.target.value)}
          placeholder="Paste the lead text here."
          style={{
            width: "100%",
            minHeight: 110,
            padding: 12,
            borderRadius: 10,
            border: "1px solid #d1d5db",
            resize: "vertical",
            boxSizing: "border-box",
            marginBottom: 12,
          }}
        />

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr 1fr",
            gap: 12,
            marginBottom: 12,
          }}
        >
          <input
            value={leadContactName}
            onChange={(e) => setLeadContactName(e.target.value)}
            placeholder="Contact name"
            style={inputBox()}
          />
          <input
            value={leadContactInfo}
            onChange={(e) => setLeadContactInfo(e.target.value)}
            placeholder="Phone or email"
            style={inputBox()}
          />
          <input
            value={leadBudget}
            onChange={(e) => setLeadBudget(e.target.value)}
            placeholder="Budget"
            style={inputBox()}
          />
        </div>

        <div
          style={{
            background: "#f8fafc",
            border: "1px solid #e5e7eb",
            borderRadius: 12,
            padding: 14,
            marginBottom: 16,
          }}
        >
          <div style={{ fontWeight: 700, marginBottom: 8 }}>
            Auto Score Preview
          </div>
          <div style={{ lineHeight: 1.8 }}>
            <div>
              Score: <strong>{scoredDraftLead.score}</strong>
            </div>
            <div>
              Bucket: <strong>{scoreBucket(scoredDraftLead.score)}</strong>
            </div>
            <div>
              Job Type:{" "}
              <strong>{detectJobType(`${leadTitle} ${leadDescription}`)}</strong>
            </div>
            <div>
              Quote Range:{" "}
              <strong>
                {quoteRangeFromLead(
                  `${leadTitle}\n${leadDescription}`,
                  scoredDraftLead.score
                )}
              </strong>
            </div>
            <div style={{ marginTop: 6 }}>
              Reasons:{" "}
              {scoredDraftLead.reasons.length
                ? scoredDraftLead.reasons.join(" • ")
                : "No strong signals yet"}
            </div>
          </div>
        </div>

        <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 18 }}>
          <button onClick={() => void addLead()} style={buttonStyle()}>
            Save Lead + Score
          </button>

          <select
            value={leadStatusFilter}
            onChange={(e) => setLeadStatusFilter(e.target.value)}
            style={{
              padding: "12px",
              borderRadius: 10,
              border: "1px solid #d1d5db",
            }}
          >
            <option value="all">All statuses</option>
            <option value="new">New</option>
            <option value="contacted">Contacted</option>
            <option value="quoted">Quoted</option>
            <option value="won">Won</option>
          </select>

          <select
            value={leadBucketFilter}
            onChange={(e) => setLeadBucketFilter(e.target.value)}
            style={{
              padding: "12px",
              borderRadius: 10,
              border: "1px solid #d1d5db",
            }}
          >
            <option value="all">All buckets</option>
            <option value="Hot">Hot</option>
            <option value="Warm">Warm</option>
            <option value="Cold">Cold</option>
          </select>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr 1fr",
            gap: 16,
            alignItems: "start",
          }}
        >
          <PipelineColumn
            title={`Hot 🔥 (${hotLeads.length})`}
            bg="#fff1f2"
            leads={hotLeads}
            onStatus={updateLeadStatus}
            onDelete={deleteLead}
            onLoadReply={setOutput}
          />
          <PipelineColumn
            title={`Warm (${warmLeads.length})`}
            bg="#fffbeb"
            leads={warmLeads}
            onStatus={updateLeadStatus}
            onDelete={deleteLead}
            onLoadReply={setOutput}
          />
          <PipelineColumn
            title={`Cold (${coldLeads.length})`}
            bg="#f8fafc"
            leads={coldLeads}
            onStatus={updateLeadStatus}
            onDelete={deleteLead}
            onLoadReply={setOutput}
          />
        </div>
      </div>
    </div>
  );
}